
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 27 14:08:30 CET 2008
//----------------------------------------------------
package ansascraper;

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */

    public static final int TITLE = 2;
    public static final int error = 1;
    public static final int TEXT = 3;
    public static final int EOF = 0;
}

