DocumentClassifier: JLex.CAlloc Class Reference
JLex.CAlloc
JLex.CAlloc Class Reference
Static Package Functions
static CDfa newCDfa (CSpec spec)
static CNfaPair newCNfaPair ()
static CNfaPair newNLPair (CSpec spec)
static CNfa newCNfa (CSpec spec)
Detailed Description
Definition at line 3737 of file Main.java.
Member Function Documentation
static CDfa JLex.CAlloc.newCDfa (CSpec spec) [static, package]
Definition at line 3743 of file Main.java.
References JLex.CSpec.m_dfa_states.
      {
        CDfa dfa;
        dfa = new CDfa(spec.m_dfa_states.size());
        spec.m_dfa_states.addElement(dfa);
        return dfa;
      }
static CNfaPair JLex.CAlloc.newCNfaPair () [static, package]
Definition at line 3760 of file Main.java.
Referenced by JLex.CAlloc.newNLPair().
      {
        CNfaPair pair = new CNfaPair();
        return pair;
      }
static CNfaPair JLex.CAlloc.newNLPair (CSpec spec) [static, package]
Definition at line 3773 of file Main.java.
References JLex.CSet.add(), JLex.CSpec.m_dtrans_ncols, JLex.CNfa.m_edge, JLex.CNfaPair.m_end, JLex.CNfa.m_next, JLex.CNfa.m_next2, JLex.CNfa.m_set, JLex.CNfaPair.m_start, JLex.CAlloc.newCNfa(), and JLex.CAlloc.newCNfaPair().
{
    CNfaPair pair = newCNfaPair();
    pair.m_end=newCNfa(spec); // newline accepting state
    pair.m_start=newCNfa(spec); // new state with two epsilon edges
    pair.m_start.m_next = newCNfa(spec);
    pair.m_start.m_next.m_edge = CNfa.CCL;
    pair.m_start.m_next.m_set = new CSet();
    pair.m_start.m_next.m_set.add('\n');
    if (spec.m_dtrans_ncols-CSpec.NUM_PSEUDO > 2029) {
      pair.m_start.m_next.m_set.add(2028); /*U+2028 is LS, the line separator*/
      pair.m_start.m_next.m_set.add(2029); /*U+2029 is PS, the paragraph sep.*/
    }
    pair.m_start.m_next.m_next = pair.m_end; // accept '\n', U+2028, or U+2029
    pair.m_start.m_next2 = newCNfa(spec);
    pair.m_start.m_next2.m_edge = '\r';
    pair.m_start.m_next2.m_next = newCNfa(spec);
    pair.m_start.m_next2.m_next.m_next = pair.m_end; // accept '\r';
    pair.m_start.m_next2.m_next.m_next2 = newCNfa(spec);
    pair.m_start.m_next2.m_next.m_next2.m_edge = '\n';
    pair.m_start.m_next2.m_next.m_next2.m_next = pair.m_end; // accept '\r\n';
    return pair;
  }
static CNfa JLex.CAlloc.newCNfa (CSpec spec) [static, package]
Definition at line 3801 of file Main.java.
References JLex.CNfa.m_edge, and JLex.CSpec.m_nfa_states.
Referenced by JLex.CAlloc.newNLPair().
      {
        CNfa p;
        /* UNDONE: Buffer this? */
        p = new CNfa();
        /*p.m_label = spec.m_nfa_states.size();*/
        spec.m_nfa_states.addElement(p);
        p.m_edge = CNfa.EPSILON;
        return p;
      }
The documentation for this class was generated from the following file:
src/ansascraper/JLex/Main.java