DocumentClassifier: JLex.CNfa2Dfa Class Reference
JLex.CNfa2Dfa
JLex.CNfa2Dfa Class Reference
Package Functions
CNfa2Dfa ()
void make_dfa (CLexGen lexGen, CSpec spec)
void move (Vector nfa_set, SparseBitSet nfa_bit, int b, CBunch bunch)
Private Member Functions
void set (CLexGen lexGen, CSpec spec)
void reset ()
void make_dtrans ()
void free_dfa_states ()
void free_nfa_states ()
void e_closure (CBunch bunch)
void sortStates (Vector nfa_set)
CDfa get_unmarked ()
int add_to_dstates (CBunch bunch)
int in_dstates (CBunch bunch)
Private Attributes
CSpec m_spec
int m_unmarked_dfa
CLexGen m_lexGen
Static Private Attributes
static final int NOT_IN_DSTATES = -1
Detailed Description
Definition at line 3112 of file Main.java.
Constructor & Destructor Documentation
JLex.CNfa2Dfa.CNfa2Dfa () [package]
Definition at line 3130 of file Main.java.
References JLex.CNfa2Dfa.reset().
      {
        reset();
      }
Member Function Documentation
void JLex.CNfa2Dfa.set (CLexGen lexGen, CSpec spec) [private]
Definition at line 3141 of file Main.java.
References JLex.CNfa2Dfa.m_lexGen, JLex.CNfa2Dfa.m_spec, and JLex.CNfa2Dfa.m_unmarked_dfa.
      {
        m_lexGen = lexGen;
        m_spec = spec;
        m_unmarked_dfa = 0;
      }
void JLex.CNfa2Dfa.reset () [private]
Definition at line 3156 of file Main.java.
References JLex.CNfa2Dfa.m_lexGen, JLex.CNfa2Dfa.m_spec, and JLex.CNfa2Dfa.m_unmarked_dfa.
Referenced by JLex.CNfa2Dfa.CNfa2Dfa(), and JLex.CNfa2Dfa.make_dfa().
      {
        m_lexGen = null;
        m_spec = null;
        m_unmarked_dfa = 0;
      }
void JLex.CNfa2Dfa.make_dfa (CLexGen lexGen, CSpec spec) [package]
Definition at line 3169 of file Main.java.
References JLex.CNfa2Dfa.free_dfa_states(), JLex.CNfa2Dfa.free_nfa_states(), JLex.CSpec.m_dfa_states, JLex.CNfa2Dfa.m_spec, JLex.CSpec.m_verbose, JLex.CNfa2Dfa.make_dtrans(), and JLex.CNfa2Dfa.reset().
Referenced by JLex.CLexGen.userRules().
      {
        int i;
        reset();
        set(lexGen,spec);
        make_dtrans();
        free_nfa_states();
        if (m_spec.m_verbose && true == CUtility.OLD_DUMP_DEBUG)
          {
            System.out.println(m_spec.m_dfa_states.size()
                               + " DFA states in original machine.");
          }
        free_dfa_states();
      }
void JLex.CNfa2Dfa.make_dtrans () [private]
Definition at line 3196 of file Main.java.
References JLex.CNfa2Dfa.add_to_dstates(), JLex.CNfa2Dfa.e_closure(), JLex.CNfa2Dfa.get_unmarked(), JLex.CNfa2Dfa.in_dstates(), JLex.CDfa.m_accept, JLex.CDTrans.m_accept, JLex.CBunch.m_accept, JLex.CBunch.m_accept_index, JLex.CDfa.m_anchor, JLex.CDTrans.m_anchor, JLex.CBunch.m_anchor, JLex.CSpec.m_dfa_states, JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_ncols, JLex.CSpec.m_dtrans_vector, JLex.CDfa.m_label, JLex.CNfa.m_label, JLex.CDfa.m_mark, JLex.CDfa.m_nfa_bit, JLex.CBunch.m_nfa_bit, JLex.CDfa.m_nfa_set, JLex.CBunch.m_nfa_set, JLex.CNfa2Dfa.m_spec, JLex.CSpec.m_state_dtrans, JLex.CSpec.m_state_rules, JLex.CNfa2Dfa.m_unmarked_dfa, JLex.CNfa2Dfa.move(), JLex.CNfa2Dfa.NOT_IN_DSTATES, JLex.SparseBitSet.set(), and JLex.CNfa2Dfa.sortStates().
Referenced by JLex.CNfa2Dfa.make_dfa().
      {
        CDfa next;
        CDfa dfa;
        CBunch bunch;
        int i;
        int nextstate;
        int size;
        CDTrans dtrans;
        CNfa nfa;
        int istate;
        int nstates;
        System.out.print("Working on DFA states.");
        /* Reference passing type and initializations. */
        bunch = new CBunch();
        m_unmarked_dfa = 0;
        /* Allocate mapping array. */
        nstates = m_spec.m_state_rules.length;
        m_spec.m_state_dtrans = new int[nstates];
        for (istate = 0; nstates > istate; ++istate)
          {
            /* CSA bugfix: if we skip all zero size rules, then
               an specification with no rules produces an illegal
               lexer (0 states) instead of a lexer that rejects
               everything (1 nonaccepting state). [27-Jul-1999]
            if (0 == m_spec.m_state_rules[istate].size())
              {
                m_spec.m_state_dtrans[istate] = CDTrans.F;
                continue;
              }
            */
            /* Create start state and initialize fields. */
            bunch.m_nfa_set = (Vector) m_spec.m_state_rules[istate].clone();
            sortStates(bunch.m_nfa_set);
            bunch.m_nfa_bit = new SparseBitSet();
            /* Initialize bit set. */
            size = bunch.m_nfa_set.size();
            for (i = 0; size > i; ++i)
              {
                nfa = (CNfa) bunch.m_nfa_set.elementAt(i);
                bunch.m_nfa_bit.set(nfa.m_label);
              }
            bunch.m_accept = null;
            bunch.m_anchor = CSpec.NONE;
            bunch.m_accept_index = CUtility.INT_MAX;
            e_closure(bunch);
            add_to_dstates(bunch);
            m_spec.m_state_dtrans[istate] = m_spec.m_dtrans_vector.size();
            /* Main loop of CDTrans creation. */
            while (null != (dfa = get_unmarked()))
              {
                System.out.print(".");
                System.out.flush();
                if (CUtility.DEBUG)
                  {
                    CUtility.ASSERT(false == dfa.m_mark);
                  }
                /* Get first unmarked node, then mark it. */
                dfa.m_mark = true;
                /* Allocate new CDTrans, then initialize fields. */
                dtrans = new CDTrans(m_spec.m_dtrans_vector.size(),m_spec);
                dtrans.m_accept = dfa.m_accept;
                dtrans.m_anchor = dfa.m_anchor;
                /* Set CDTrans array for each character transition. */
                for (i = 0; i < m_spec.m_dtrans_ncols; ++i)
                  {
                    if (CUtility.DEBUG)
                      {
                        CUtility.ASSERT(0 <= i);
                        CUtility.ASSERT(m_spec.m_dtrans_ncols > i);
                      }
                    /* Create new dfa set by attempting character transition. */
                    move(dfa.m_nfa_set,dfa.m_nfa_bit,i,bunch);
                    if (null != bunch.m_nfa_set)
                      {
                        e_closure(bunch);
                      }
                    if (CUtility.DEBUG)
                      {
                        CUtility.ASSERT((null == bunch.m_nfa_set
                                         && null == bunch.m_nfa_bit)
                                        || (null != bunch.m_nfa_set
                                            && null != bunch.m_nfa_bit));
                      }
                    /* Create new state or set state to empty. */
                    if (null == bunch.m_nfa_set)
                      {
                        nextstate = CDTrans.F;
                      }
                    else
                      {
                        nextstate = in_dstates(bunch);
                        if (NOT_IN_DSTATES == nextstate)
{
                            nextstate = add_to_dstates(bunch);
                          }
                      }
                    if (CUtility.DEBUG)
                      {
                        CUtility.ASSERT(nextstate < m_spec.m_dfa_states.size());
                      }
                    dtrans.m_dtrans[i] = nextstate;
                  }
                if (CUtility.DEBUG)
                  {
                    CUtility.ASSERT(m_spec.m_dtrans_vector.size() == dfa.m_label);
                  }
                m_spec.m_dtrans_vector.addElement(dtrans);
              }
          }
        System.out.println();
      }
void JLex.CNfa2Dfa.free_dfa_states () [private]
Definition at line 3339 of file Main.java.
References JLex.CSpec.m_dfa_sets, JLex.CSpec.m_dfa_states, and JLex.CNfa2Dfa.m_spec.
Referenced by JLex.CNfa2Dfa.make_dfa().
      {
        m_spec.m_dfa_states = null;
        m_spec.m_dfa_sets = null;
      }
void JLex.CNfa2Dfa.free_nfa_states () [private]
Definition at line 3350 of file Main.java.
References JLex.CSpec.m_nfa_start, JLex.CSpec.m_nfa_states, JLex.CNfa2Dfa.m_spec, and JLex.CSpec.m_state_rules.
Referenced by JLex.CNfa2Dfa.make_dfa().
      {
        /* UNDONE: Remove references to nfas from within dfas. */
        /* UNDONE: Don't free CAccepts. */
        m_spec.m_nfa_states = null;
        m_spec.m_nfa_start = null;
        m_spec.m_state_rules = null;
      }
void JLex.CNfa2Dfa.e_closure (CBunch bunch) [private]
Definition at line 3366 of file Main.java.
References JLex.SparseBitSet.get(), JLex.CNfa.m_accept, JLex.CBunch.m_accept, JLex.CBunch.m_accept_index, JLex.CAccept.m_action, JLex.CAccept.m_action_read, JLex.CNfa.m_anchor, JLex.CBunch.m_anchor, JLex.CNfa.m_edge, JLex.CNfa.m_label, JLex.CNfa.m_next, JLex.CNfa.m_next2, JLex.CBunch.m_nfa_bit, JLex.CBunch.m_nfa_set, JLex.SparseBitSet.set(), and JLex.CNfa2Dfa.sortStates().
Referenced by JLex.CNfa2Dfa.make_dtrans().
      {
        Stack nfa_stack;
        int size;
        int i;
        CNfa state;
        /* Debug checks. */
        if (CUtility.DEBUG)
          {
            CUtility.ASSERT(null != bunch);
            CUtility.ASSERT(null != bunch.m_nfa_set);
            CUtility.ASSERT(null != bunch.m_nfa_bit);
          }
        bunch.m_accept = null;
        bunch.m_anchor = CSpec.NONE;
        bunch.m_accept_index = CUtility.INT_MAX;
        /* Create initial stack. */
        nfa_stack = new Stack();
        size = bunch.m_nfa_set.size();
        for (i = 0; i < size; ++i)
          {
            state = (CNfa) bunch.m_nfa_set.elementAt(i);
            if (CUtility.DEBUG)
              {
                CUtility.ASSERT(bunch.m_nfa_bit.get(state.m_label));
              }
            nfa_stack.push(state);
          }
        /* Main loop. */
        while (false == nfa_stack.empty())
          {
            state = (CNfa) nfa_stack.pop();
            if (CUtility.OLD_DUMP_DEBUG)
              {
                if (null != state.m_accept)
                  {
                    System.out.println("Looking at accepting state " + state.m_label
                                       + " with <"
                                       + (new String(state.m_accept.m_action,0,
                                                     state.m_accept.m_action_read))
                                       + ">");
                  }
              }
            if (null != state.m_accept
                && state.m_label < bunch.m_accept_index)
              {
                bunch.m_accept_index = state.m_label;
                bunch.m_accept = state.m_accept;
                bunch.m_anchor = state.m_anchor;
                if (CUtility.OLD_DUMP_DEBUG)
                  {
                    System.out.println("Found accepting state " + state.m_label
                                       + " with <"
                                       + (new String(state.m_accept.m_action,0,
                                                     state.m_accept.m_action_read))
                                       + ">");
                  }
                if (CUtility.DEBUG)
                  {
                    CUtility.ASSERT(null != bunch.m_accept);
                    CUtility.ASSERT(CSpec.NONE == bunch.m_anchor
                                    || 0 != (bunch.m_anchor & CSpec.END)
                                    || 0 != (bunch.m_anchor & CSpec.START));
                  }
              }
            if (CNfa.EPSILON == state.m_edge)
              {
                if (null != state.m_next)
                  {
                    if (false == bunch.m_nfa_set.contains(state.m_next))
                      {
                        if (CUtility.DEBUG)
{
                            CUtility.ASSERT(false == bunch.m_nfa_bit.get(state.m_next.m_label));
                          }
                        bunch.m_nfa_bit.set(state.m_next.m_label);
                        bunch.m_nfa_set.addElement(state.m_next);
                        nfa_stack.push(state.m_next);
                      }
                  }
                if (null != state.m_next2)
                  {
                    if (false == bunch.m_nfa_set.contains(state.m_next2))
                      {
                        if (CUtility.DEBUG)
{
                            CUtility.ASSERT(false == bunch.m_nfa_bit.get(state.m_next2.m_label));
                          }
                        bunch.m_nfa_bit.set(state.m_next2.m_label);
                        bunch.m_nfa_set.addElement(state.m_next2);
                        nfa_stack.push(state.m_next2);
                      }
                  }
              }
          }
        if (null != bunch.m_nfa_set)
          {
            sortStates(bunch.m_nfa_set);
          }
        return;
      }
void JLex.CNfa2Dfa.move (Vector nfa_set, SparseBitSet nfa_bit, int b, CBunch bunch) [package]
Definition at line 3491 of file Main.java.
References JLex.CSet.contains(), JLex.CNfa.m_edge, JLex.CNfa.m_label, JLex.CNfa.m_next, JLex.CBunch.m_nfa_bit, JLex.CBunch.m_nfa_set, JLex.CNfa.m_set, JLex.SparseBitSet.set(), JLex.SparseBitSet.size, and JLex.CNfa2Dfa.sortStates().
Referenced by JLex.CNfa2Dfa.make_dtrans().
      {
        int size;
        int index;
        CNfa state;
        bunch.m_nfa_set = null;
        bunch.m_nfa_bit = null;
        size = nfa_set.size();
        for (index = 0; index < size; ++index)
          {
            state = (CNfa) nfa_set.elementAt(index);
            if (b == state.m_edge
                || (CNfa.CCL == state.m_edge
                    && true == state.m_set.contains(b)))
              {
                if (null == bunch.m_nfa_set)
                  {
                    if (CUtility.DEBUG)
                      {
                        CUtility.ASSERT(null == bunch.m_nfa_bit);
                      }
                    bunch.m_nfa_set = new Vector();
                    /*bunch.m_nfa_bit
                        = new SparseBitSet(m_spec.m_nfa_states.size());*/
                    bunch.m_nfa_bit = new SparseBitSet();
                  }
                bunch.m_nfa_set.addElement(state.m_next);
                /*System.out.println("Size of bitset: " + bunch.m_nfa_bit.size());
                System.out.println("Reference index: " + state.m_next.m_label);
                System.out.flush();*/
                bunch.m_nfa_bit.set(state.m_next.m_label);
              }
          }
        if (null != bunch.m_nfa_set)
          {
            if (CUtility.DEBUG)
              {
                CUtility.ASSERT(null != bunch.m_nfa_bit);
              }
            sortStates(bunch.m_nfa_set);
          }
        return;
      }
void JLex.CNfa2Dfa.sortStates (Vector nfa_set) [private]
Definition at line 3552 of file Main.java.
References JLex.CNfa.m_label.
Referenced by JLex.CNfa2Dfa.e_closure(), JLex.CNfa2Dfa.make_dtrans(), and JLex.CNfa2Dfa.move().
      {
        CNfa elem;
        int begin;
        int size;
        int index;
        int value;
        int smallest_index;
        int smallest_value;
        CNfa begin_elem;
        size = nfa_set.size();
        for (begin = 0; begin < size; ++begin)
          {
            elem = (CNfa) nfa_set.elementAt(begin);
            smallest_value = elem.m_label;
            smallest_index = begin;
            for (index = begin + 1; index < size; ++index)
              {
                elem = (CNfa) nfa_set.elementAt(index);
                value = elem.m_label;
                if (value < smallest_value)
                  {
                    smallest_index = index;
                    smallest_value = value;
                  }
              }
            begin_elem = (CNfa) nfa_set.elementAt(begin);
            elem = (CNfa) nfa_set.elementAt(smallest_index);
            nfa_set.setElementAt(elem,begin);
            nfa_set.setElementAt(begin_elem,smallest_index);
          }
        if (CUtility.OLD_DEBUG)
          {
            System.out.print("NFA vector indices: ");
            for (index = 0; index < size; ++index)
              {
                elem = (CNfa) nfa_set.elementAt(index);
                System.out.print(elem.m_label + " ");
              }
            System.out.println();
          }
        return;
      }
CDfa JLex.CNfa2Dfa.get_unmarked () [private]
Definition at line 3610 of file Main.java.
References JLex.CSpec.m_dfa_states, JLex.CNfa2Dfa.m_lexGen, JLex.CDfa.m_mark, JLex.CDfa.m_nfa_set, JLex.CNfa2Dfa.m_spec, JLex.CNfa2Dfa.m_unmarked_dfa, JLex.CSpec.m_verbose, and JLex.CLexGen.print_set().
Referenced by JLex.CNfa2Dfa.make_dtrans().
      {
        int size;
        CDfa dfa;
        size = m_spec.m_dfa_states.size();
        while (m_unmarked_dfa < size)
          {
            dfa = (CDfa) m_spec.m_dfa_states.elementAt(m_unmarked_dfa);
            if (false == dfa.m_mark)
              {
                if (CUtility.OLD_DUMP_DEBUG)
                  {
                    System.out.print("*");
                    System.out.flush();
                  }
                if (m_spec.m_verbose && true == CUtility.OLD_DUMP_DEBUG)
                  {
                    System.out.println("---------------");
                    System.out.print("working on DFA state "
                                     + m_unmarked_dfa
                                     + " = NFA states: ");
                    m_lexGen.print_set(dfa.m_nfa_set);
                    System.out.println();
                  }
                return dfa;
              }
            ++m_unmarked_dfa;
          }
        return null;
      }
int JLex.CNfa2Dfa.add_to_dstates (CBunch bunch) [private]
Definition at line 3659 of file Main.java.
References JLex.SparseBitSet.clone(), JLex.CDfa.m_accept, JLex.CBunch.m_accept, JLex.CDfa.m_anchor, JLex.CBunch.m_anchor, JLex.CSpec.m_dfa_sets, JLex.CDfa.m_label, JLex.CNfa2Dfa.m_lexGen, JLex.CDfa.m_mark, JLex.CDfa.m_nfa_bit, JLex.CBunch.m_nfa_bit, JLex.CDfa.m_nfa_set, JLex.CBunch.m_nfa_set, JLex.CNfa2Dfa.m_spec, and JLex.CLexGen.print_set().
Referenced by JLex.CNfa2Dfa.make_dtrans().
      {
        CDfa dfa;
        if (CUtility.DEBUG)
          {
            CUtility.ASSERT(null != bunch.m_nfa_set);
            CUtility.ASSERT(null != bunch.m_nfa_bit);
            CUtility.ASSERT(null != bunch.m_accept
                            || CSpec.NONE == bunch.m_anchor);
          }
        /* Allocate, passing CSpec so dfa label can be set. */
        dfa = CAlloc.newCDfa(m_spec);
        /* Initialize fields, including the mark field. */
        dfa.m_nfa_set = (Vector) bunch.m_nfa_set.clone();
        dfa.m_nfa_bit = (SparseBitSet) bunch.m_nfa_bit.clone();
        dfa.m_accept = bunch.m_accept;
        dfa.m_anchor = bunch.m_anchor;
        dfa.m_mark = false;
        /* Register dfa state using BitSet in CSpec Hashtable. */
        m_spec.m_dfa_sets.put(dfa.m_nfa_bit,dfa);
        /*registerCDfa(dfa);*/
        if (CUtility.OLD_DUMP_DEBUG)
          {
            System.out.print("Registering set : ");
            m_lexGen.print_set(dfa.m_nfa_set);
            System.out.println();
          }
        return dfa.m_label;
      }
int JLex.CNfa2Dfa.in_dstates (CBunch bunch) [private]
Definition at line 3701 of file Main.java.
References JLex.CSpec.m_dfa_sets, JLex.CDfa.m_label, JLex.CNfa2Dfa.m_lexGen, JLex.CBunch.m_nfa_bit, JLex.CBunch.m_nfa_set, JLex.CNfa2Dfa.m_spec, JLex.CNfa2Dfa.NOT_IN_DSTATES, and JLex.CLexGen.print_set().
Referenced by JLex.CNfa2Dfa.make_dtrans().
      {
        CDfa dfa;
        if (CUtility.OLD_DEBUG)
          {
            System.out.print("Looking for set : ");
            m_lexGen.print_set(bunch.m_nfa_set);
          }
        dfa = (CDfa) m_spec.m_dfa_sets.get(bunch.m_nfa_bit);
        if (null != dfa)
          {
            if (CUtility.OLD_DUMP_DEBUG)
              {
                System.out.println(" FOUND!");
              }
            return dfa.m_label;
          }
        if (CUtility.OLD_DUMP_DEBUG)
          {
            System.out.println(" NOT FOUND!");
          }
        return NOT_IN_DSTATES;
      }
Member Data Documentation
CSpec JLex.CNfa2Dfa.m_spec [private]
Definition at line 3117 of file Main.java.
Referenced by JLex.CNfa2Dfa.add_to_dstates(), JLex.CNfa2Dfa.free_dfa_states(), JLex.CNfa2Dfa.free_nfa_states(), JLex.CNfa2Dfa.get_unmarked(), JLex.CNfa2Dfa.in_dstates(), JLex.CNfa2Dfa.make_dfa(), JLex.CNfa2Dfa.make_dtrans(), JLex.CNfa2Dfa.reset(), and JLex.CNfa2Dfa.set().
int JLex.CNfa2Dfa.m_unmarked_dfa [private]
Definition at line 3118 of file Main.java.
Referenced by JLex.CNfa2Dfa.get_unmarked(), JLex.CNfa2Dfa.make_dtrans(), JLex.CNfa2Dfa.reset(), and JLex.CNfa2Dfa.set().
CLexGen JLex.CNfa2Dfa.m_lexGen [private]
Definition at line 3119 of file Main.java.
Referenced by JLex.CNfa2Dfa.add_to_dstates(), JLex.CNfa2Dfa.get_unmarked(), JLex.CNfa2Dfa.in_dstates(), JLex.CNfa2Dfa.reset(), and JLex.CNfa2Dfa.set().
final int JLex.CNfa2Dfa.NOT_IN_DSTATES = -1 [static, private]
Definition at line 3124 of file Main.java.
Referenced by JLex.CNfa2Dfa.in_dstates(), and JLex.CNfa2Dfa.make_dtrans().
The documentation for this class was generated from the following file:
src/ansascraper/JLex/Main.java