DocumentClassifier: documentclassifier.DocumentClassifierView Class Reference
documentclassifier.DocumentClassifierView
documentclassifier.DocumentClassifierView Class Reference
Public Member Functions
DocumentClassifierView (SingleFrameApplication app)
void openDocument ()
void preferenceChange (PreferenceChangeEvent evt)
void showAboutBox ()
void showHelp ()
void stopCurrentTask ()
boolean isDocumentRead ()
void setDocumentRead (boolean b)
boolean isURLValid ()
void setURLValid (boolean b)
boolean isTaskRunning ()
void setTaskRunning (boolean b)
Task readInputDocument ()
Task rankDocuments ()
Static Public Member Functions
static void showErrorMessage (String msg)
Private Member Functions
void initComponents ()
void openDocument (String path) throws Exception
void clickDocuments (java.awt.event.MouseEvent evt)
void openPreferences (java.awt.event.ActionEvent evt)
void fieldURLCaretUpdate (javax.swing.event.CaretEvent evt)
void keyPressedDocuments (java.awt.event.KeyEvent evt)
Private Attributes
DocumentClassifierApp application
ResourceBundle documentClassifierViewResources = ResourceBundle.getBundle("documentclassifier/resources/DocumentClassifierView")
Document currentQuery
LinkedList< Map
< String, Object > > infoDocuments
PreferencesDialog preferencesDialog
Task currentTask
DefaultTableModel tableModel
JFileChooser fileChooser
boolean documentRead = false
boolean URLValid = false
boolean taskRunning = false
Classes
class ReadInputDocumentTask
Detailed Description
This class represents the main frame of the application.
Author:
Salvo Danilo Giuffrida (giuffsalvo@hotmail.it, salvodanilogiuffrida@gmail.com)
Definition at line 67 of file DocumentClassifierView.java.
Constructor & Destructor Documentation
documentclassifier.DocumentClassifierView.DocumentClassifierView (SingleFrameApplication app)
The input map associated with the JTable that visualizes the list of documents ranked to the current query is modified, so that when the user presses the key 'Enter' on an entry of the JTable, instead of the default behavior (scrolling to the next entry), a personalized one can be implemented.
I set the property 'UpdatePolicy' of the caret associated to the JTextArea 'textAreaOutput', which contains the status messages during the execution of the various tasks (scraping of the query document, classification, validation)
An event of type 'PreferenceChangeEvent' is forcefully generated (this class is a registered listener of it), to check what it the current chosen metric, and eventually change the label on the first column of the table, from "Cosine" to "Distance", in case the chosen metric is the Bhattacharrya distance
Definition at line 96 of file DocumentClassifierView.java.
References documentclassifier.DocumentClassifierView.application, documentclassifier.DocumentClassifierApp.getMetric(), documentclassifier.DocumentClassifierApp.getPreferences(), documentclassifier.DocumentClassifierView.infoDocuments, documentclassifier.DocumentClassifierView.initComponents(), documentclassifier.DocumentClassifierView.preferenceChange(), and documentclassifier.DocumentClassifierView.tableModel.
{
        super(app);
        initComponents();
        infoDocuments = new LinkedList<Map<String, Object>>();
        this.getFrame().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        listDocuments.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "none");
        ((DefaultCaret) textAreaOutput.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        application = (DocumentClassifierApp) app;
        tableModel = (DefaultTableModel) listDocuments.getModel();
        preferenceChange(new PreferenceChangeEvent(application.getPreferences(), MapDefaultPreferences.METRIC, application.getMetric(false)));
        // Do NOT touch the following section!
        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);
        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String) (evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                //messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer) (evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }
Member Function Documentation
void documentclassifier.DocumentClassifierView.initComponents () [private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor
Definition at line 189 of file DocumentClassifierView.java.
References documentclassifier.DocumentClassifierView.fieldURLCaretUpdate().
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
{
        mainPanel = new javax.swing.JPanel();
        fieldURL = new javax.swing.JTextField();
        buttonRead = new javax.swing.JButton();
        scrollPanelLabelTitle = new javax.swing.JScrollPane();
        labelTitle = new javax.swing.JLabel();
        buttonStop = new javax.swing.JButton();
        buttonFind = new javax.swing.JButton();
        toolbar = new javax.swing.JToolBar();
        separatorInitial = new javax.swing.JToolBar.Separator();
        buttonOpen = new javax.swing.JButton();
        separatorOpenTraining = new javax.swing.JToolBar.Separator();
        buttonValidation = new javax.swing.JButton();
        splitPaneVertical = new javax.swing.JSplitPane();
        splitPaneHorizontal = new javax.swing.JSplitPane();
        scrollPaneRankedDocuments = new javax.swing.JScrollPane();
        listDocuments = new javax.swing.JTable();
        scrollPaneLabelText = new javax.swing.JScrollPane();
        labelText = new javax.swing.JTextArea();
        scrollPaneTextAreaOutput = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        trainingMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem esciMenuItem = new javax.swing.JMenuItem();
        modifyMenu = new javax.swing.JMenu();
        menuItemPreferenze = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        metricsGroup = new javax.swing.ButtonGroup();
        mainPanel.setName("mainPanel"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(documentclassifier.DocumentClassifierApp.class).getContext().getResourceMap(DocumentClassifierView.class);
        fieldURL.setToolTipText(resourceMap.getString("fieldURL.toolTipText")); // NOI18N
        fieldURL.setName("fieldURL"); // NOI18N
        fieldURL.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fieldURLCaretUpdate(evt);
            }
        });
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(documentclassifier.DocumentClassifierApp.class).getContext().getActionMap(DocumentClassifierView.class, this);
        buttonRead.setAction(actionMap.get("readInputDocument")); // NOI18N
        buttonRead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRead.setName("buttonRead"); // NOI18N
        scrollPanelLabelTitle.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPanelLabelTitle.setFont(scrollPanelLabelTitle.getFont());
        scrollPanelLabelTitle.setName("scrollPanelLabelTitle"); // NOI18N
        labelTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        labelTitle.setToolTipText(resourceMap.getString("labelTitle.toolTipText")); // NOI18N
        labelTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTitle.setName("labelTitle"); // NOI18N
        scrollPanelLabelTitle.setViewportView(labelTitle);
        buttonStop.setAction(actionMap.get("stopCurrentTask")); // NOI18N
        buttonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonStop.setName("buttonStop"); // NOI18N
        buttonFind.setAction(actionMap.get("rankDocuments")); // NOI18N
        buttonFind.setName("buttonFind"); // NOI18N
        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setName("toolbar"); // NOI18N
        separatorInitial.setName("separatorInitial"); // NOI18N
        toolbar.add(separatorInitial);
        buttonOpen.setAction(actionMap.get("openDocument")); // NOI18N
        buttonOpen.setFocusable(false);
        buttonOpen.setName("buttonOpen"); // NOI18N
        buttonOpen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        toolbar.add(buttonOpen);
        separatorOpenTraining.setName("separatorOpenTraining"); // NOI18N
        toolbar.add(separatorOpenTraining);
        buttonValidation.setAction(actionMap.get("Validation")); // NOI18N
        buttonValidation.setFocusable(false);
        buttonValidation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonValidation.setName("buttonValidation"); // NOI18N
        buttonValidation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(buttonValidation);
        splitPaneVertical.setDividerLocation(420);
        splitPaneVertical.setDividerSize(10);
        splitPaneVertical.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPaneVertical.setContinuousLayout(true);
        splitPaneVertical.setName("splitPaneVertical"); // NOI18N
        splitPaneVertical.setOneTouchExpandable(true);
        splitPaneHorizontal.setDividerLocation(360);
        splitPaneHorizontal.setDividerSize(10);
        splitPaneHorizontal.setContinuousLayout(true);
        splitPaneHorizontal.setName("splitPaneHorizontal"); // NOI18N
        splitPaneHorizontal.setOneTouchExpandable(true);
        scrollPaneRankedDocuments.setName("scrollPaneRankedDocuments"); // NOI18N
        listDocuments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cosine", "Categories", "Title"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listDocuments.setToolTipText(resourceMap.getString("listDocuments.toolTipText")); // NOI18N
        listDocuments.setColumnSelectionAllowed(true);
        listDocuments.setName("listDocuments"); // NOI18N
        listDocuments.getTableHeader().setReorderingAllowed(false);
        listDocuments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickDocuments(evt);
            }
        });
        listDocuments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedDocuments(evt);
            }
        });
        scrollPaneRankedDocuments.setViewportView(listDocuments);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("documentclassifier/resources/DocumentClassifierView"); // NOI18N
        listDocuments.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        listDocuments.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("listDocuments.title0.Cosine")); // NOI18N
        listDocuments.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("listDocuments.title1")); // NOI18N
        listDocuments.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("listDocuments.title2")); // NOI18N
        splitPaneHorizontal.setRightComponent(scrollPaneRankedDocuments);
        scrollPaneLabelText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneLabelText.setName("scrollPaneLabelText"); // NOI18N
        labelText.setColumns(20);
        labelText.setEditable(false);
        labelText.setLineWrap(true);
        labelText.setRows(1);
        labelText.setToolTipText(resourceMap.getString("labelText.toolTipText")); // NOI18N
        labelText.setWrapStyleWord(true);
        labelText.setName("labelText"); // NOI18N
        scrollPaneLabelText.setViewportView(labelText);
        splitPaneHorizontal.setLeftComponent(scrollPaneLabelText);
        splitPaneVertical.setTopComponent(splitPaneHorizontal);
        scrollPaneTextAreaOutput.setName("scrollPaneTextAreaOutput"); // NOI18N
        textAreaOutput.setEditable(false);
        textAreaOutput.setLineWrap(true);
        textAreaOutput.setToolTipText(resourceMap.getString("textAreaOutput.toolTipText")); // NOI18N
        textAreaOutput.setWrapStyleWord(true);
        textAreaOutput.setName("textAreaOutput"); // NOI18N
        scrollPaneTextAreaOutput.setViewportView(textAreaOutput);
        splitPaneVertical.setRightComponent(scrollPaneTextAreaOutput);
        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRead, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFind)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPaneVertical)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFind)
                    .addComponent(scrollPanelLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPaneVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonRead, buttonStop, fieldURL});
        menuBar.setName("menuBar"); // NOI18N
        fileMenu.setMnemonic('F');
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        openMenuItem.setAction(actionMap.get("openDocument")); // NOI18N
        openMenuItem.setText(resourceMap.getString("openMenuItem.text")); // NOI18N
        openMenuItem.setName("openMenuItem"); // NOI18N
        fileMenu.add(openMenuItem);
        trainingMenuItem.setAction(actionMap.get("Validation")); // NOI18N
        trainingMenuItem.setText(resourceMap.getString("validationMenuItem.text")); // NOI18N
        trainingMenuItem.setName("validationMenuItem"); // NOI18N
        fileMenu.add(trainingMenuItem);
        esciMenuItem.setAction(actionMap.get("quit")); // NOI18N
        esciMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        esciMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(esciMenuItem);
        menuBar.add(fileMenu);
        modifyMenu.setMnemonic('M');
        modifyMenu.setText(resourceMap.getString("modifyMenu.text")); // NOI18N
        modifyMenu.setName("modifyMenu"); // NOI18N
        menuItemPreferenze.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuItemPreferenze.setText(resourceMap.getString("menuItemPreferences.text")); // NOI18N
        menuItemPreferenze.setName("menuItemPreferences"); // NOI18N
        menuItemPreferenze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPreferences(evt);
            }
        });
        modifyMenu.add(menuItemPreferenze);
        menuBar.add(modifyMenu);
        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N
        helpMenuItem.setAction(actionMap.get("showHelp")); // NOI18N
        helpMenuItem.setText(resourceMap.getString("helpMenuItem.text")); // NOI18N
        helpMenuItem.setName("helpMenuItem"); // NOI18N
        helpMenu.add(helpMenuItem);
        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);
        statusPanel.setName("statusPanel"); // NOI18N
        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N
        statusMessageLabel.setName("statusMessageLabel"); // NOI18N
        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N
        progressBar.setName("progressBar"); // NOI18N
        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 635, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );
        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents
void documentclassifier.DocumentClassifierView.openDocument ()
Action associated with the men entry File->Open: It shows a JFileChooser, used to choose from the local filesystem a query document to classify.
Definition at line 518 of file DocumentClassifierView.java.
{
        try {
            if (fileChooser == null) {
                fileChooser = new JFileChooser();
                fileChooser.setCurrentDirectory(new File("."));
            }
            if (fileChooser.showOpenDialog(this.getComponent()) == JFileChooser.APPROVE_OPTION) {
                fieldURL.setText(fileChooser.getSelectedFile().getCanonicalPath());
            }
        } catch (IOException ex) {
            showErrorMessage(ex.toString());
        }
    }
void documentclassifier.DocumentClassifierView.openDocument (String path) throws Exception [private]
Method that opens a document (whose path is specified in input) in an external viewer.
Parameters:
path The path of the document that must be opened.
Exceptions:
java.lang.Exception
Definition at line 538 of file DocumentClassifierView.java.
{
        //Desktop.getDesktop().browse(new URI(path));
        if (System.getProperty("os.name").toLowerCase().indexOf("windows") > -1) {
            Runtime.getRuntime().exec("cmd /c " + path);
        } else if (System.getProperty("os.name").toLowerCase().indexOf("mac") > -1) {
            Runtime.getRuntime().exec("open " + path);
        } else {
            Runtime.getRuntime().exec("firefox " + path);
        }
    }
void documentclassifier.DocumentClassifierView.clickDocuments (java.awt.event.MouseEvent evt) [private]
When the user double clicks on one or more of the entries of the beforementioned list, this method handles the opening of the corresponding documents in an external viewer.
Parameters:
evt The MouseEvent generated by the double click of the user.
Definition at line 556 of file DocumentClassifierView.java.
                                                               {//GEN-FIRST:event_clickDocuments
        try {
            int numberDoubleClicks = evt.getClickCount() / 2;
            if (numberDoubleClicks >= 1) {
                for (int index : listDocuments.getSelectedRows()) {
                    String path = (String) infoDocuments.get(index).get("Path");
                    openDocument(path);
                }
            }
        } catch (Exception ex) {
            showErrorMessage(ex.toString());
        }
}//GEN-LAST:event_clickDocuments
void documentclassifier.DocumentClassifierView.openPreferences (java.awt.event.ActionEvent evt) [private]
This method handles the ActionEvent generated when the user clicks, or presses 'Enter', on the men entry 'Modify->Preferences': Its task is to show the panel for the configuration of the various program's preferences.
Parameters:
evt The ActionEvent generated when the user clicks or presses 'Enter'.
Definition at line 576 of file DocumentClassifierView.java.
                                                             {//GEN-FIRST:event_openPreferences
    preferencesDialog = new PreferencesDialog(this, true);
    preferencesDialog.setVisible(true);
}//GEN-LAST:event_openPreferences
void documentclassifier.DocumentClassifierView.fieldURLCaretUpdate (javax.swing.event.CaretEvent evt) [private]
This method is called every time the caret of the JTextField containing the URL of the query document changes its position.
Parameters:
evt The CaretEvent generated every time the caret of the JTextField containing the URL of the query document changes its position (for example because of the insertion or deletion of characters from it).
Every time the position of the caret changes, the method controls if this event has been triggered by the removal or the insertion of characters in the JTextField. In case character have been removed, and the field has become empty, the property 'indirizzoValido', which controls the enabling of the task for scraping the current query document (LeggiDocumentoInputTask), is set to "false", otherwise to "true".
Definition at line 590 of file DocumentClassifierView.java.
Referenced by documentclassifier.DocumentClassifierView.initComponents().
                                                                   {//GEN-FIRST:event_fieldURLCaretUpdate
    String URLText = fieldURL.getText();
    if (!URLText.isEmpty()) {
        setURLValid(true);
    } else {
        setURLValid(false);
    }
}//GEN-LAST:event_fieldURLCaretUpdate
void documentclassifier.DocumentClassifierView.keyPressedDocuments (java.awt.event.KeyEvent evt) [private]
This method is called every time that a button of the keyboard is pressed, while the GUI has its focus on the list of documents of the training set ranked to the current query document.
Parameters:
evt The KeyEvent generated every tume that a button of the keyboard is pressed, while the GUI has its focus on the list of documents of the training set del training set ranked to the current query document.
If the button that has been pressed is 'Enter', all selected documents are opened
Definition at line 614 of file DocumentClassifierView.java.
                                                              {//GEN-FIRST:event_keyPressedDocuments
    try {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            for (int index : listDocuments.getSelectedRows()) {
                String path = (String) infoDocuments.get(index).get(documentClassifierViewResources.getString("listDocuments.title3"));
                openDocument(path);
            }
        }
    } catch (Exception ex) {
        showErrorMessage(ex.toString());
    }
}//GEN-LAST:event_keyPressedDocuments
static void documentclassifier.DocumentClassifierView.showErrorMessage (String msg) [static]
This method shows an error message inside a JOptionPane, in order to make visualization of exceptions' messages more user-friendly.
Parameters:
msg Message that must be showed.
Definition at line 635 of file DocumentClassifierView.java.
{
        JOptionPane.showMessageDialog(null, msg, ResourceBundle.getBundle("documentclassifier/resources/DocumentClassifierView").getString("messages.Error"), JOptionPane.ERROR_MESSAGE);
    }
void documentclassifier.DocumentClassifierView.preferenceChange (PreferenceChangeEvent evt)
This method implements the interface PreferenceChangeListener, and is called every time that a value of a preferences node is removed or modified.
Parameters:
evt The PreferenceChangeEvent generated every time that a value of a preferences node is removed or modified.
The method first controls if the modified value is the one containing the name of the current metric or of the current scraper.
In the 1st case, the method changes the title of the 1st column in the JTable containing information about each document of the training set, ranked to the current query:
If the current metric is now TF-IDF, the name of the 1st column of the JTable is set to "Cosine".
Otherwise, if the current metric becomes the Bhattacharrya distance, that is set to "Distance".
The identifiers of the other two columns of the JTable (the 2nd and the 3rd) remain constant.
In the 2nd case, instead, the current scraper instance has been changed, therefore the property 'documentRead' (which controls the activation of OrdinaDocumentiTask, the classification task for the current document) is set to "false". This is done to force the user to read, with the new chosen scraper, the current query document, before trying to classify it.
Definition at line 646 of file DocumentClassifierView.java.
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
{
        if(evt.getKey().equals(MapDefaultPreferences.METRIC)) {
            Vector<String> columnIdentifiers=new Vector<String>();
            if(application.getMetric(false).equals("TF-IDF")) {
                columnIdentifiers.add(documentClassifierViewResources.getString("listDocuments.title0.Cosine"));
            }
            else {
                columnIdentifiers.add(documentClassifierViewResources.getString("listDocuments.title0.Distance"));
            }
            columnIdentifiers.add(tableModel.getColumnName(tableModel.getColumnCount()-2));
            columnIdentifiers.add(tableModel.getColumnName(tableModel.getColumnCount()-1));
            tableModel.setColumnIdentifiers(columnIdentifiers);
        } else if (evt.getKey().equals(MapDefaultPreferences.SCRAPER)) {
            setDocumentRead(false);
        }
    }
void documentclassifier.DocumentClassifierView.showAboutBox ()
Action that shows a JOptionPane containing information about the program, its author, etc...
Definition at line 691 of file DocumentClassifierView.java.
{
        if (aboutBox == null) {
            JFrame mainFrame = DocumentClassifierApp.getApplication().getMainFrame();
            aboutBox = new DocumentClassifierAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DocumentClassifierApp.getApplication().show(aboutBox);
    }
void documentclassifier.DocumentClassifierView.showHelp ()
Action that shows the online help.
Definition at line 704 of file DocumentClassifierView.java.
{
        JOptionPane.showMessageDialog(this.getFrame(), (Object) new String("Help"), "DocumentClassifier - Help", JOptionPane.INFORMATION_MESSAGE);
    }
void documentclassifier.DocumentClassifierView.stopCurrentTask ()
Action that stops the current foreground task, if there is one running (that is, if the property 'taskRunning' is set to "true").
Definition at line 713 of file DocumentClassifierView.java.
{
        DocumentClassifierApp.getInstance().getContext().getTaskMonitor().getForegroundTask().cancel(true);
        //currentTask.cancel(true);
    }
boolean documentclassifier.DocumentClassifierView.isDocumentRead ()
Definition at line 724 of file DocumentClassifierView.java.
{
        return documentRead;
    }
void documentclassifier.DocumentClassifierView.setDocumentRead (boolean b)
Definition at line 728 of file DocumentClassifierView.java.
{
        boolean old = isDocumentRead();
        documentRead = b;
        firePropertyChange("documentRead", old, isDocumentRead());
    }
boolean documentclassifier.DocumentClassifierView.isURLValid ()
Definition at line 738 of file DocumentClassifierView.java.
{
        return URLValid;
    }
void documentclassifier.DocumentClassifierView.setURLValid (boolean b)
Definition at line 742 of file DocumentClassifierView.java.
{
        boolean old = isURLValid();
        this.URLValid = b;
        firePropertyChange("URLValid", old, isURLValid());
    }
boolean documentclassifier.DocumentClassifierView.isTaskRunning ()
Definition at line 752 of file DocumentClassifierView.java.
{
        return taskRunning;
    }
void documentclassifier.DocumentClassifierView.setTaskRunning (boolean b)
Definition at line 756 of file DocumentClassifierView.java.
{
        boolean old = isTaskRunning();
        this.taskRunning = b;
        firePropertyChange("taskRunning", old, isTaskRunning());
    }
Task documentclassifier.DocumentClassifierView.readInputDocument ()
Action, and associated background task, to extract the title and text from the document whose URL has been specified in the JTextField, and which represents the current query. The action is enabled only if the property 'indirizzoValido' is set "true", something that happens only if the JTextField of the URL is not empty.
Returns:
A reference to the background task associated with the action.
Definition at line 771 of file DocumentClassifierView.java.
{
        currentTask=new ReadInputDocumentTask(application, fieldURL.getText());
        return currentTask;
    }
Task documentclassifier.DocumentClassifierView.rankDocuments ()
Action, and associated background task, to rank the documents of the training set to the current query document. The action is enabled only if the property 'documentRead' is set to "true", that is if the query document has been correctly read from the URL provided in the JTextField.
Returns:
A reference to the background task associated with the action.
Definition at line 902 of file DocumentClassifierView.java.
{
        currentTask = new RankDocumentsTask(getApplication(), currentQuery, application.getTrainingSet(), application.getKNN(false), true);
        return currentTask;
    }
Member Data Documentation
DocumentClassifierApp documentclassifier.DocumentClassifierView.application [private]
The application this JFrame refers to.
Definition at line 72 of file DocumentClassifierView.java.
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
ResourceBundle documentclassifier.DocumentClassifierView.documentClassifierViewResources = ResourceBundle.getBundle("documentclassifier/resources/DocumentClassifierView") [private]
Resource bundle for this class' localized resources.
Definition at line 76 of file DocumentClassifierView.java.
Document documentclassifier.DocumentClassifierView.currentQuery [private]
This variable mantains the reference to the current query document.
Definition at line 80 of file DocumentClassifierView.java.
LinkedList<Map<String, Object> > documentclassifier.DocumentClassifierView.infoDocuments [private]
This is a list of maps 'String'->'Object', each one containing information on a document of the training set, and whose content is used when we want to visualize such information on the appropriate JTable after the ranking phase.
Definition at line 86 of file DocumentClassifierView.java.
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
PreferencesDialog documentclassifier.DocumentClassifierView.preferencesDialog [private]
Each entry in the list aforementioned is made of a vector of objects containing information on a document of the training set (Bhattacharrya distance/Cosine of the angle with the query document, Category, Title), and a map that represents the document's histogram.
Definition at line 92 of file DocumentClassifierView.java.
Task documentclassifier.DocumentClassifierView.currentTask [private]
Definition at line 93 of file DocumentClassifierView.java.
DefaultTableModel documentclassifier.DocumentClassifierView.tableModel [private]
Definition at line 94 of file DocumentClassifierView.java.
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
JFileChooser documentclassifier.DocumentClassifierView.fileChooser [private]
Definition at line 511 of file DocumentClassifierView.java.
boolean documentclassifier.DocumentClassifierView.documentRead = false [private]
Property 'documentRead', which indicates if the document referenced by the URL in the JTextField has already been read or not by the current scraper, and therefore its title and text are available.
Definition at line 723 of file DocumentClassifierView.java.
boolean documentclassifier.DocumentClassifierView.URLValid = false [private]
Property 'URLValid', which indicates if the address specified in the JTextField is valid or not.
Definition at line 737 of file DocumentClassifierView.java.
boolean documentclassifier.DocumentClassifierView.taskRunning = false [private]
Property 'taskRunning', which indicates in every moment if there is a running background task.
Definition at line 751 of file DocumentClassifierView.java.
The documentation for this class was generated from the following file:
src/documentclassifier/DocumentClassifierView.java