/*
 * TrainingDialog.java
 *
 * Created on 25 giugno 2008, 22.31
 */
package documentclassifier;

import org.jdesktop.application.Action;

/**
 *
 * @author  mahone
 */
public class TrainingDialog extends javax.swing.JDialog {

    private int KNNMaximum;
    
    /** Creates new form TrainingDialog */
    public TrainingDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        KNNMaximum = 1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKNN = new javax.swing.JLabel();
        sliderKNN = new javax.swing.JSlider();
        separator = new javax.swing.JSeparator();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(documentclassifier.DocumentClassifierApp.class).getContext().getResourceMap(TrainingDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setLocationByPlatform(true);
        setModal(true);
        setName("Form"); // NOI18N

        labelKNN.setText(resourceMap.getString("labelKNN.text")); // NOI18N
        labelKNN.setName("labelKNN"); // NOI18N

        sliderKNN.setMaximum(DocumentClassifierApp.getApplication().getKNNMaximum());
        sliderKNN.setMinimum(1);
        sliderKNN.setValue(1);
        sliderKNN.setName("sliderKNN"); // NOI18N

        separator.setName("separator"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(documentclassifier.DocumentClassifierApp.class).getContext().getActionMap(TrainingDialog.class, this);
        buttonOK.setAction(actionMap.get("OK")); // NOI18N
        buttonOK.setText(resourceMap.getString("buttonOK.text")); // NOI18N
        buttonOK.setName("buttonOK"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelKNN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderKNN, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                    .addComponent(buttonOK))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelKNN)
                    .addComponent(sliderKNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOK)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    @Action
    public void OK() {
        KNNMaximum=sliderKNN.getValue();
        setVisible(false);
    }
    
    public int getKNNMaximum() {
        return KNNMaximum;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel labelKNN;
    private javax.swing.JSeparator separator;
    private javax.swing.JSlider sliderKNN;
    // End of variables declaration//GEN-END:variables

}
