DocumentClassifier: JLex.CSet Class Reference
JLex.CSet
JLex.CSet Class Reference
Package Functions
CSet ()
void complement ()
void add (int i)
void addncase (char c)
boolean contains (int i)
void mimic (CSet set)
void map (CSet set, int[] mapping)
Private Attributes
SparseBitSet m_set
boolean m_complement
Detailed Description
Definition at line 4587 of file Main.java.
Constructor & Destructor Documentation
JLex.CSet.CSet () [package]
Definition at line 4599 of file Main.java.
References JLex.CSet.m_complement, and JLex.CSet.m_set.
    {
      m_set = new SparseBitSet();
      m_complement = false;
    }
Member Function Documentation
void JLex.CSet.complement () [package]
Definition at line 4610 of file Main.java.
References JLex.CSet.m_complement.
Referenced by JLex.CMakeNfa.term().
      {
        m_complement = true;
      }
void JLex.CSet.add (int i) [package]
Definition at line 4620 of file Main.java.
References JLex.CSet.m_set, and JLex.SparseBitSet.set().
Referenced by JLex.CMakeNfa.machine(), JLex.CAlloc.newNLPair(), and JLex.CMakeNfa.term().
      {
        m_set.set(i);
      }
void JLex.CSet.addncase (char c) [package]
Definition at line 4631 of file Main.java.
Referenced by JLex.CMakeNfa.term().
      {
        /* Do this in a Unicode-friendly way. */
        /* (note that duplicate adds have no effect) */
        add(c);
        add(Character.toLowerCase(c));
        add(Character.toTitleCase(c));
        add(Character.toUpperCase(c));
      }
boolean JLex.CSet.contains (int i) [package]
Definition at line 4647 of file Main.java.
References JLex.SparseBitSet.get(), JLex.CSet.m_complement, and JLex.CSet.m_set.
Referenced by JLex.CSimplifyNfa.computeClasses(), and JLex.CNfa2Dfa.move().
      {
        boolean result;
        result = m_set.get(i);
        if (m_complement)
          {
            return (false == result);
          }
        return result;
      }
void JLex.CSet.mimic (CSet set) [package]
Definition at line 4667 of file Main.java.
References JLex.SparseBitSet.clone(), JLex.CSet.m_complement, and JLex.CSet.m_set.
Referenced by JLex.CNfa.mimic().
      {
        m_complement = set.m_complement;
        m_set = (SparseBitSet) set.m_set.clone();
      }
void JLex.CSet.map (CSet set, int[] mapping) [package]
Map set using character classes [CSA]
Definition at line 4676 of file Main.java.
References JLex.SparseBitSet.clearAll(), JLex.SparseBitSet.elements(), JLex.CSet.m_complement, JLex.CSet.m_set, and JLex.SparseBitSet.set().
Referenced by JLex.CSimplifyNfa.simplify().
{
    m_complement = set.m_complement;
    m_set.clearAll();
    for (Enumeration e=set.m_set.elements(); e.hasMoreElements(); ) {
      int old_value =((Integer)e.nextElement()).intValue();
      if (old_value<mapping.length) // skip unmapped characters
        m_set.set(mapping[old_value]);
    }
  }
Member Data Documentation
SparseBitSet JLex.CSet.m_set [private]
Definition at line 4592 of file Main.java.
Referenced by JLex.CSet.add(), JLex.CSet.contains(), JLex.CSet.CSet(), JLex.CSet.map(), and JLex.CSet.mimic().
boolean JLex.CSet.m_complement [private]
Definition at line 4593 of file Main.java.
Referenced by JLex.CSet.complement(), JLex.CSet.contains(), JLex.CSet.CSet(), JLex.CSet.map(), and JLex.CSet.mimic().
The documentation for this class was generated from the following file:
src/ansascraper/JLex/Main.java