DocumentClassifier: documentclassifier.DocumentClassifierApp Class Reference
documentclassifier.DocumentClassifierApp
documentclassifier.DocumentClassifierApp Class Reference
Public Member Functions
void preferenceChange (PreferenceChangeEvent event)
Static Public Member Functions
static
DocumentClassifierApp getApplication ()
static void main (String[] args)
Protected Member Functions
void initialize (String[] args)
void startup ()
String[] readDocument (InputStream IS) throws Exception
String getTrainingSetDirectory (boolean defaultValue)
boolean isRemovalStopWords (boolean defaultValue)
String getStopWordsList (boolean defaultValue)
String getLogFile (boolean defaultValue)
boolean isLogging (boolean defaultValue)
MapDefaultPreferences getMapPreferences ()
String getMetric (boolean defaultValue)
int getKFold (boolean defaultValue)
int getKFoldMaximum ()
int getKFoldMinimum ()
int getKNN (boolean defaultValue)
void setKNN (int K)
int getKNNMaximum ()
int getKNNMinimum ()
int getMaximumKNNValidation (boolean defaultValue)
boolean isOverwriteLogFile (boolean defaultValue)
Preferences getPreferences ()
Scraper getScraper (boolean defaultValue)
String getScrapersPackageName ()
String getStemmersPackageName ()
boolean isStemming (boolean defaultValue)
String getStemmer (boolean defaultValue)
boolean isStratified (boolean defaultValue)
synchronized boolean generateTrainingSet (String path) throws Exception
synchronized Set
< Set< Document > > getTrainingSet ()
synchronized int getTrainingSetSize ()
boolean isVisualizeCurrentDocument (boolean defaultValue)
boolean isVisualizeListRankedDocuments (boolean defaultValue)
Static Protected Member Functions
static List< Class > getClassesForPackage (String packagename) throws ClassNotFoundException
Private Member Functions
void cancelPreferences ()
Scraper getScraperInstance (String nomeClasse)
Private Attributes
ResourceBundle documentClassifierAppResources = java.util.ResourceBundle.getBundle("documentclassifier/resources/DocumentClassifierApp")
Set< Set< Document > > trainingSet
int trainingSetSize = 0
Scraper Scraper
String trainingSetDirectory
String logFile
String stopWordsList
String metric
boolean isRemovalStopWords
boolean isStemming
boolean isStratified
boolean isLogging
boolean isOverwriteLogFile
boolean isVisualizeCurrentDocument
boolean isVisualizeDocumentsList
String currentStemmer
int KNN
int KFold
int maximumKNNValidation
Static Private Attributes
static final Preferences preferences = Preferences.userRoot()
static final
MapDefaultPreferences mapDefaultPreferences = new MapDefaultPreferences()
Detailed Description
Main class of the application
Beside the implementation of some methods of the class SingleFrameApplication, which is extended to personalize its behaviour, this class contains:
A method (preferenceChange), which implements the interface PreferenceChangeListener, called each time that the values of one or more preferences are modified (by methods of this or other classes of the application, which register this class as their PreferenceChangeListener)
Methods to get the values of the various preferences
A method (generateTrainingSet) to (re)generate the training set every time that it is necessary
A method (readDocument) to read the title and the text of a document from the file system, and from these create an instance of the class Document
Author:
Salvo Danilo Giuffrida (giuffsalvo@hotmail.it, salvodanilogiuffrida@gmail.com)
See also:
SingleFrameApplication
Definition at line 50 of file DocumentClassifierApp.java.
Member Function Documentation
void documentclassifier.DocumentClassifierApp.initialize (String[] args) [protected]
Responsible for initializations that must occur before the GUI is constructed by startup.
Parameters:
args The arguments passed to the application through the command line.
Definition at line 92 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.preferenceChange(), and documentclassifier.DocumentClassifierApp.preferences.
{
        super.initialize(args);
        /*
         * A PreferenceChangeEvent is manually generated, to force during the startup of the
         * program the reading of the preferences (from the node represented by the variable
         * 'preferenze'), and the initialization of the corresponding internal variables of the
         * class.
         */
        preferenceChange(new PreferenceChangeEvent(preferences, "All", "All"));
    }
void documentclassifier.DocumentClassifierApp.startup () [protected]
At startup create and show the main frame of the application.
Definition at line 107 of file DocumentClassifierApp.java.
{
        show(new DocumentClassifierView(this));
    }
static DocumentClassifierApp documentclassifier.DocumentClassifierApp.getApplication () [static]
A convenient static getter for the application instance.
Returns:
the instance of DocumentClassifierApp.
Definition at line 115 of file DocumentClassifierApp.java.
{
        return Application.getInstance(DocumentClassifierApp.class);
    }
static void documentclassifier.DocumentClassifierApp.main (String[] args) [static]
Main method launching the application.
Parameters:
args
Definition at line 123 of file DocumentClassifierApp.java.
{
        launch(DocumentClassifierApp.class, args);
    }
void documentclassifier.DocumentClassifierApp.cancelPreferences () [private]
Method that cancels all the preferences' values, restoring them to their default ones.
Definition at line 130 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.preferences.
Referenced by documentclassifier.DocumentClassifierApp.preferenceChange().
{
        try {
            preferences.clear();
        } catch (BackingStoreException ex) {
            DocumentClassifierView.showErrorMessage(ex.toString());
        }
    }
void documentclassifier.DocumentClassifierApp.preferenceChange (PreferenceChangeEvent event)
Method that implements the interface 'PreferenceChangeListener'.
It is invoked each time a preference of the node represented by the variable 'preferenze' is modified, changing the value and/or the state of one or more components of the JDialog PreferencesDialog. When a preference is modified, this method updates the value of the corresponding variable inside this class.
Parameters:
event The PreferenceChangeEvent that must be managed.
Definition at line 149 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.cancelPreferences(), documentclassifier.DocumentClassifierApp.currentStemmer, documentclassifier.DocumentClassifierApp.generateTrainingSet(), documentclassifier.DocumentClassifierApp.getScraperInstance(), documentclassifier.DocumentClassifierApp.isLogging, documentclassifier.DocumentClassifierApp.isOverwriteLogFile, documentclassifier.DocumentClassifierApp.isRemovalStopWords, documentclassifier.DocumentClassifierApp.isStemming, documentclassifier.DocumentClassifierApp.isStratified, documentclassifier.DocumentClassifierApp.isVisualizeCurrentDocument, documentclassifier.DocumentClassifierApp.isVisualizeDocumentsList, documentclassifier.DocumentClassifierApp.KFold, documentclassifier.DocumentClassifierApp.KNN, documentclassifier.DocumentClassifierApp.logFile, documentclassifier.DocumentClassifierApp.mapDefaultPreferences, documentclassifier.DocumentClassifierApp.maximumKNNValidation, documentclassifier.DocumentClassifierApp.metric, documentclassifier.DocumentClassifierApp.preferences, documentclassifier.DocumentClassifierApp.stopWordsList, and documentclassifier.DocumentClassifierApp.trainingSetDirectory.
Referenced by documentclassifier.DocumentClassifierApp.initialize().
{
        try {
            String eventKey = event.getKey();
            String currentKey, defaultValue;
            currentKey=MapDefaultPreferences.SCRAPER;
            Scraper=getScraperInstance(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.isREMOVALSTOPWORDS;
            isRemovalStopWords = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.STOPWORDSLIST;
            defaultValue=mapDefaultPreferences.get(currentKey);
            stopWordsList = preferences.get(currentKey, defaultValue);
            if (!new File(stopWordsList).isFile()) {
                String message = "The specified stopwords file ("+stopWordsList+") is not valid,\n";
                stopWordsList = defaultValue;
                if (new File(stopWordsList).isFile() && isRemovalStopWords) {
                    DocumentClassifierView.showErrorMessage(message + "the default value is used (" + stopWordsList + " )");
                } else if (!new File(stopWordsList).isFile() && isRemovalStopWords) {
                    DocumentClassifierView.showErrorMessage(message + "the default file (" + stopWordsList + ") is not present,\n"
                            +"the removal of stopwords has been disabled");
                    isRemovalStopWords = false;
                    preferences.put(MapDefaultPreferences.isREMOVALSTOPWORDS, String.valueOf(isRemovalStopWords));
                }
            }
            currentKey=MapDefaultPreferences.isSTEMMING;
            isStemming = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.STEMMER;
            currentStemmer = preferences.get(currentKey, mapDefaultPreferences.get(currentKey));
            //(Re)Generation of the training set
            currentKey=MapDefaultPreferences.TRAININGSETDIRECTORY;
            trainingSetDirectory=preferences.get(currentKey, defaultValue);
            if (eventKey.equals("All") || eventKey.equals(MapDefaultPreferences.isSTEMMING) || eventKey.equals(MapDefaultPreferences.STOPWORDSLIST)) {
                defaultValue=mapDefaultPreferences.get(currentKey);
                if(!generateTrainingSet(trainingSetDirectory)) {
                    trainingSetDirectory=defaultValue;
                    String message="The path specified for the training set directory is not valid, ";
                    if(generateTrainingSet(trainingSetDirectory)) {
                        DocumentClassifierView.showErrorMessage(message +
                                "the default value is used ("+trainingSetDirectory + ")");
                    }
                    else {
                        DocumentClassifierView.showErrorMessage(message +
                                "and the default directory ("+trainingSetDirectory + ") is not present.\n"
                                +"Classification not possible");
                    }
                }
            }
            currentKey=MapDefaultPreferences.METRIC;
            metric = preferences.get(currentKey, mapDefaultPreferences.get(currentKey));
            currentKey=MapDefaultPreferences.KNN;
            KNN = Integer.parseInt(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.MAXKNNVALIDATION;
            maximumKNNValidation = Integer.parseInt(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.KFOLD;
            KFold = Integer.parseInt(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.isSTRATIFIED;
            isStratified = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.isLOGGING;
            isLogging = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.LOGFILE;
            logFile = preferences.get(currentKey, mapDefaultPreferences.get(currentKey));
            currentKey=MapDefaultPreferences.isOVERWRITELOGFILE;
            isOverwriteLogFile = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.isVISUALIZECURRENTDOCUMENT;
            isVisualizeCurrentDocument = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
            currentKey=MapDefaultPreferences.isVISUALIZELISTRANKEDDOCUMENTS;
            isVisualizeDocumentsList = Boolean.parseBoolean(preferences.get(currentKey, mapDefaultPreferences.get(currentKey)));
        } catch (Exception ex) {
            DocumentClassifierView.showErrorMessage(ex.toString());
            cancelPreferences();
        }
    }
String [] documentclassifier.DocumentClassifierApp.readDocument (InputStream IS) throws Exception [protected]
Method that reads from an InputStream (FileInputStream, NetworkInputStream, ecc..) the title and the text of the document associated with it, using an appropriate scraper, and it returns them inside a vector of strings (position 0: Title, position 1: Text).
Parameters:
IS The InputStream from where reading the document.
Returns:
The title and the text of the extracted document, inside a String vector made of two elements.
Exceptions:
Exception
Definition at line 247 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.generateTrainingSet().
{
        return Scraper.getDocument(IS);
    }
static List<Class> documentclassifier.DocumentClassifierApp.getClassesForPackage (String packagename) throws ClassNotFoundException [static, protected]
Method that returns the list of classes inside the package provided in input.
Parameters:
packagename The name of the package we want to know the classes of.
Returns:
The list of classes (as instances of the class Class) present inside the specified package.
Exceptions:
java.lang.ClassNotFoundException
Definition at line 259 of file DocumentClassifierApp.java.
{
        // This will hold a list of directories matching the pckgname.
        // There may be more than one if a package is split over multiple jars/paths
        List<Class> classes = new ArrayList<Class>();
        ArrayList<File> directories = new ArrayList<File>();
        try {
            ClassLoader cld = Thread.currentThread().getContextClassLoader();
            if (cld == null) {
                throw new ClassNotFoundException("Can't get class loader.");
            }
            // Ask for all resources for the path
            Enumeration<URL> resources = cld.getResources(packagename.replace('.', '/'));
            while (resources.hasMoreElements()) {
                URL res = resources.nextElement();
                if (res.getProtocol().equalsIgnoreCase("jar")) {
                    JarURLConnection conn = (JarURLConnection) res.openConnection();
                    JarFile jar = conn.getJarFile();
                    for (JarEntry e : Collections.list(jar.entries())) {
                        if (e.getName().startsWith(packagename.replace('.', '/')) && e.getName().endsWith(".class") && !e.getName().contains("$")) {
                            String className =
                                    e.getName().replace("/", ".").substring(0, e.getName().length() - 6);
                            //System.out.println(className);
                            classes.add(Class.forName(className));
                        }
                    }
                } else {
                    directories.add(new File(URLDecoder.decode(res.getPath(), "UTF-8")));
                }
            }
        } catch (NullPointerException x) {
            throw new ClassNotFoundException(packagename + " does not appear to be a valid package (Null pointer exception)");
        } catch (UnsupportedEncodingException encex) {
            throw new ClassNotFoundException(packagename + " does not appear to be a valid package (Unsupported encoding)");
        } catch (IOException ioex) {
            throw new ClassNotFoundException("IOException was thrown when trying to get all resources for " + packagename);
        }
        // For every directory identified capture all the .class files
        for (File directory : directories) {
            if (directory.exists()) {
                // Get the list of the files contained in the package
                String[] files = directory.list();
                for (String file : files) {
                    // we are only interested in .class files
                    if (file.endsWith(".class")) {
                        // removes the .class extension
                        classes.add(Class.forName(packagename + '.' + file.substring(0, file.length() - 6)));
                    }
                }
            } else {
                throw new ClassNotFoundException(packagename + " (" + directory.getPath() +
                        ") does not appear to be a valid package");
            }
        }
        return classes;
    }
String documentclassifier.DocumentClassifierApp.getTrainingSetDirectory (boolean defaultValue) [protected]
The following methods allow read access to the internal variables of this class that correspond to one of the program's preferences. Each one of these methods takes in input a boolean value, which indicates if the caller must get the default value of the corresponding variable, or the actual one. Method that returns the path of the training set directory.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The path of the training set directory.
Definition at line 331 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.mapDefaultPreferences, and documentclassifier.DocumentClassifierApp.trainingSetDirectory.
{
        return (defaultValue) ? mapDefaultPreferences.get(MapDefaultPreferences.TRAININGSETDIRECTORY) : trainingSetDirectory;
    }
boolean documentclassifier.DocumentClassifierApp.isRemovalStopWords (boolean defaultValue) [protected]
Method that returns a boolean value which indicates if the removal of stopwords from documents is enabled or not.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value which indicates if the removal of stopwords from documents is enabled or not.
Definition at line 342 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isRemovalStopWords, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isREMOVALSTOPWORDS)): isRemovalStopWords;
    }
String documentclassifier.DocumentClassifierApp.getStopWordsList (boolean defaultValue) [protected]
Method that returns the path of the file containing the list of stopwords.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The path of the file containing the list of stopwords.
Definition at line 353 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.mapDefaultPreferences, and documentclassifier.DocumentClassifierApp.stopWordsList.
{
        return (defaultValue) ? mapDefaultPreferences.get(MapDefaultPreferences.STOPWORDSLIST) : stopWordsList;
    }
String documentclassifier.DocumentClassifierApp.getLogFile (boolean defaultValue) [protected]
Method that returns the path of the log file.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The path of the log file.
Definition at line 364 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.logFile, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? mapDefaultPreferences.get(MapDefaultPreferences.LOGFILE) : logFile;
    }
boolean documentclassifier.DocumentClassifierApp.isLogging (boolean defaultValue) [protected]
Method that returns a boolean value indicating if logging of messages during validation is enabled or not.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value indicating if logging of messages during validation is enabled or not.
Definition at line 375 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isLogging, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isLOGGING)) : isLogging;
    }
MapDefaultPreferences documentclassifier.DocumentClassifierApp.getMapPreferences () [protected]
Method that returns the reference to the map "name"->"default value" of each preference.
Returns:
The reference to the map "name"->"default value" of each preference.
Definition at line 384 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return mapDefaultPreferences;
    }
String documentclassifier.DocumentClassifierApp.getMetric (boolean defaultValue) [protected]
Method that returns the name of the metric currently used to calculate the distance between each document of the training set and the query document.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The name of the metric.
Definition at line 396 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.mapDefaultPreferences, and documentclassifier.DocumentClassifierApp.metric.
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
{
        return (defaultValue) ? mapDefaultPreferences.get(MapDefaultPreferences.METRIC) : metric;
    }
int documentclassifier.DocumentClassifierApp.getKFold (boolean defaultValue) [protected]
Method that returns the current value of K for K-Fold cross validation.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The current value of K for K-Fold cross validation.
Definition at line 407 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.KFold, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
Referenced by documentclassifier.PreferencesDialog.initComponents().
{
        return (defaultValue) ? Integer.parseInt(mapDefaultPreferences.get(MapDefaultPreferences.KFOLD)): KFold;
    }
int documentclassifier.DocumentClassifierApp.getKFoldMaximum () [protected]
Method that returns the maximum value of K for K-Fold cross validation, dependant on the dimension of the training set.
This value is used by the class PreferencesDialog during the drawing of its GUI, to define the 'MaxValue' property of the JSlider associated to the value of K-Fold.
Returns:
The maximum value of K for K-Fold cross validation.
Definition at line 420 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.trainingSetSize.
Referenced by documentclassifier.PreferencesDialog.initComponents().
{
        return trainingSetSize;
    }
int documentclassifier.DocumentClassifierApp.getKFoldMinimum () [protected]
Method that returns the minimum value of K for K-Fold cross validation.
Like the previous method, this one is also used by the class PreferencesDialog during the initialization of its GUI, to define the property 'MinValue' of the JSlider associated with the value of K-Fold.
Returns:
The minimum value of K for K-Fold cross validation.
Definition at line 432 of file DocumentClassifierApp.java.
Referenced by documentclassifier.PreferencesDialog.initComponents().
{
        return 2;
    }
int documentclassifier.DocumentClassifierApp.getKNN (boolean defaultValue) [protected]
Method that returns the current value of K for K-NN.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The current value of K for K-NN.
Definition at line 443 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.KNN, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Integer.parseInt(mapDefaultPreferences.get(MapDefaultPreferences.KNN)) : KNN;
    }
void documentclassifier.DocumentClassifierApp.setKNN (int K) [protected]
Method that allows to modify the preference node containing the value of K for K-NN. This method is used only at the end of the validation phase, to set K to its optimal value.
Parameters:
K The new value for K, to substitute to the current value.
Definition at line 453 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.KNN, and documentclassifier.DocumentClassifierApp.preferences.
{
        preferences.put(MapDefaultPreferences.KNN, String.valueOf(K));
        KNN=K;
        //preferenceChange(new PreferenceChangeEvent(preferenze, MapDefaultPreferences.KNN, stringK));
    }
int documentclassifier.DocumentClassifierApp.getKNNMaximum () [protected]
Method that returns the maximum allowed value of K for K-NN, dependant on the dimension of the training set. This value is then used by yhe class PreferencesDialog during initialization of its GUI, to define the property 'MaxValue' of the JSlider that controls the value of K-NN.
Returns:
The maximum allowed value of K for K-NN.
Definition at line 466 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.trainingSetSize.
Referenced by documentclassifier.PreferencesDialog.initComponents().
{
        return trainingSetSize;
    }
int documentclassifier.DocumentClassifierApp.getKNNMinimum () [protected]
Method that returns the minimum allowed value of K for K-NN. Like the previous method, this one is used by the class PreferencesDialog during the initialization of its GUI, to define the property 'MinValue' of the JSlider that controls the value of K-NN.
Returns:
The minimum allowed value of K for K-NN.
Definition at line 477 of file DocumentClassifierApp.java.
{
        return 1;
    }
int documentclassifier.DocumentClassifierApp.getMaximumKNNValidation (boolean defaultValue) [protected]
Method that returns the maximum allowed value of K for K-NN during K-Fold cross validation
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The maximum allowed value of K for K-NN during K-Fold cross validation.
Definition at line 488 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.mapDefaultPreferences, and documentclassifier.DocumentClassifierApp.maximumKNNValidation.
{
        return (defaultValue) ? Integer.parseInt(mapDefaultPreferences.get(MapDefaultPreferences.MAXKNNVALIDATION)) : maximumKNNValidation;
    }
boolean documentclassifier.DocumentClassifierApp.isOverwriteLogFile (boolean defaultValue) [protected]
Method that returns a boolean value indicating if the log file must be overwritten every time it is opened
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value indicating if the log file must be overwritten every time it is opened.
Definition at line 499 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isOverwriteLogFile, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isOVERWRITELOGFILE)) : isOverwriteLogFile;
    }
Preferences documentclassifier.DocumentClassifierApp.getPreferences () [protected]
Method that returns the reference to the preferences node used by the application. Every class of the program that needs to access this node uses this method to get a reference to it.
Returns:
The reference to the preferences node used by the application.
Definition at line 509 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.preferences.
Referenced by documentclassifier.DocumentClassifierView.DocumentClassifierView().
{
        return preferences;
    }
Scraper documentclassifier.DocumentClassifierApp.getScraper (boolean defaultValue) [protected]
Method that returns the reference to the instance of the current scraper, used to extract the features (the terms) from documents.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The reference to the instance of the current scraper.
Definition at line 521 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.getScraperInstance(), and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? getScraperInstance(mapDefaultPreferences.get(MapDefaultPreferences.SCRAPER)) : Scraper;
    }
Scraper documentclassifier.DocumentClassifierApp.getScraperInstance (String nomeClasse) [private]
Method that returns an instance of the scraper whose complete class name is provided in input.
Parameters:
nomeClasse The complete name of the class whose instance must be returned, and that must implement the interface Scraper.
Returns:
An instance of the class whose name has been specified in input.
See also:
Scraper
Definition at line 533 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getScraper(), and documentclassifier.DocumentClassifierApp.preferenceChange().
{
        try {
            Class scraperCorrenteClass = Class.forName(nomeClasse);
            return (Scraper) scraperCorrenteClass.cast(scraperCorrenteClass.newInstance());
        } catch (Exception ex) {
            DocumentClassifierView.showErrorMessage(ex.toString());
            return null;
        }
    }
String documentclassifier.DocumentClassifierApp.getScrapersPackageName () [protected]
Method that returns the name of the package where all scrapers must be put, in order to be correctly registered and used by the program.
Returns:
The name of the package where all scrapers must be put.
Definition at line 549 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.documentClassifierAppResources.
Referenced by documentclassifier.MapDefaultPreferences.MapDefaultPreferences().
{
        return documentClassifierAppResources.getString("Application.scrapersPackageName");
    }
String documentclassifier.DocumentClassifierApp.getStemmersPackageName () [protected]
Method that returns the name of the package where all stemmers must be put, in order to be correctly registered and used by the program.
Returns:
The name of the package where all stemmers must be put.
Definition at line 559 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.documentClassifierAppResources.
Referenced by documentclassifier.MapDefaultPreferences.MapDefaultPreferences().
{
        return documentClassifierAppResources.getString("Application.stemmersPackageName");
    }
boolean documentclassifier.DocumentClassifierApp.isStemming (boolean defaultValue) [protected]
Method that returns a boolean value indicating if stemming of terms from documents is enabled or not.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value indicating if stemming of terms from documents is enabled or not.
Definition at line 570 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isStemming, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isSTEMMING)) : isStemming;
    }
String documentclassifier.DocumentClassifierApp.getStemmer (boolean defaultValue) [protected]
Method that returns the complete name of the class which implements the current stemmer.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
The complete name of the class which implements the current stemmer.
Definition at line 581 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.currentStemmer, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
Referenced by documentclassifier.Document.createHistogram().
{
        return (defaultValue) ? mapDefaultPreferences.get(MapDefaultPreferences.STEMMER) : currentStemmer;
    }
boolean documentclassifier.DocumentClassifierApp.isStratified (boolean defaultValue) [protected]
Method that returns a boolean value which indicates if the partitioning for K-Fold cross validation is stratified or not.
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value which indicates if the partitioning for K-Fold cross validation is stratified or not.
Definition at line 593 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isStratified, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isSTRATIFIED)) : isStratified;
    }
synchronized boolean documentclassifier.DocumentClassifierApp.generateTrainingSet (String path) throws Exception [protected]
Method that (Re)generates the training set from the specified input directory. The documents inside this directory must be organized inside one or more subdirectories, one for each category of the training set, and having the name of this. It is possible to have documents that belong to more than one category at the same time, by putting a copy of the same document in every subdirectory corresponding to one of the categories it belongs to. This method is declared as 'synchronized', to forbid other threads from executing in parallel one of the other two synchronized methods of this class, while the training set is being (re)generated.
Parameters:
path The path of the directory containing the training set.
Returns:
A boolean value indicating if the generation of the training set has completed without errors (true), or not (false).
Exceptions:
java.lang.Exception.
First of all, a new set of subsets of documents is created, without overwriting the current training set. If at the end of the method there hasn't been any error, the value of the variable which contains the reference to the current training set will be changed with the reference to the new one.
A new instance of the class Document is created, which represents the current document read from the file system.
If the same document (that is, a document with the same text and title) is already inside the training set, but in another category than the one corresponding to the current directory-->Instead of adding a duplicated instance of it in another category, the name of the current category is added to the set of categories of the document already present in the training set, and then a reference to its instance is added to the training set's category currently being inspected, creating in this way a graph structure (as opposed to a tree one, where every document can belong to one and only one category, which can be though as its father). So, to summarize, for each document of the training set there is only one instance, but this can be put in more than one category.
The variable 'nuovoDocumento' contains the reference to the document already present in the training set.
If I must add a new document to the training set-->I increment the variable that memorizes its total dimension.
In any case, a reference to an instance of the class 'Document' (a new one, or an already existing one) is added to the current category.
I make sure that the training set cannot be modified from this moment on.
From this moment the variable 'trainingSet' points to the new training set just created. The previous reference is then lost.
Definition at line 610 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.readDocument(), documentclassifier.DocumentClassifierApp.trainingSet, and documentclassifier.DocumentClassifierApp.trainingSetSize.
Referenced by documentclassifier.DocumentClassifierApp.preferenceChange().
{
        File dir = new File(path);
        if (dir.isDirectory()) {
            Set<Set<Document>> copyTrainingSet = Collections.synchronizedSet(new LinkedHashSet<Set<Document>>());
            trainingSetSize = 0;
            for (File D : dir.listFiles()) {
                if (D.isDirectory() && D.list().length > 0) {
                    Set<Document> documentsCurrentCategory = new LinkedHashSet<Document>();
                    for (File F : D.listFiles(new FileFilter() {
                        public boolean accept(File arg) {
                            if (arg.isDirectory()) {
                                return false;
                            } else {
                                return true;
                            }
                        }
                    })) {
                        String[] titleText = readDocument(new FileInputStream(F));
                        String titolo=titleText[0];
                        String testo=titleText[1];
                        String category=D.getName();
                        Document newDocument = new Document(titolo,testo,category,F.getCanonicalPath());
                        boolean addNewDocument=true;
                        for(Set<Document> currentSubSet : copyTrainingSet) {
                            for (Document currentDocument : currentSubSet) {
                                if (currentDocument.equals(newDocument)) {
                                    currentDocument.addCategory(category);
                                    newDocument=currentDocument;
                                    addNewDocument=false;
                                    break;
                                }
                            }
                        }
                        if(addNewDocument) {
                            trainingSetSize++;
                        }
                        documentsCurrentCategory.add(newDocument);
                    }
                    copyTrainingSet.add(documentsCurrentCategory);
                }
            }
            copyTrainingSet=Collections.unmodifiableSet(copyTrainingSet);
            trainingSet = copyTrainingSet;
            return true;
        } else {
            return false;
        }
    }
synchronized Set<Set<Document> > documentclassifier.DocumentClassifierApp.getTrainingSet () [protected]
This method returns a reference to the current training set. It is declared as 'synchronized' to avoid that, if another thread is in the meantime executing one of the other two synchronized methods of the class (for example if the training set is being regenerated), the reference to the current training set is concurrently accessed, reference that for sure will change once the method generateTrainingSet will finish, making the previous reference invalid.
Returns:
A reference to the current training set, or null if this hasn't yet been generated.
Definition at line 705 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.trainingSet.
{
        return trainingSet;
    }
synchronized int documentclassifier.DocumentClassifierApp.getTrainingSetSize () [protected]
This method returns the total dimension of the current training set, that is the number of different documents thereby present. It is declared as 'synchronized' for the same reasons of the previous method.
Returns:
The total dimension of the current training set, or 0 if this hasn't yet been created.
Definition at line 716 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.trainingSetSize.
Referenced by documentclassifier.PreferencesDialog.initComponents().
{
        return trainingSetSize;
    }
boolean documentclassifier.DocumentClassifierApp.isVisualizeCurrentDocument (boolean defaultValue) [protected]
This method returns a boolean value that indicates if the current document (its title and text) must be visualized during the validation phase (keep in mind that this slows down its execution).
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value that indicates if the current document must be visualized during the validation phase.
Definition at line 728 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isVisualizeCurrentDocument, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isVISUALIZECURRENTDOCUMENT)) : isVisualizeCurrentDocument;
    }
boolean documentclassifier.DocumentClassifierApp.isVisualizeListRankedDocuments (boolean defaultValue) [protected]
This method returns a boolean value that indicates if the list of documents of the training set, ranked to the current query document, must be visualized during the validation phase (keep in mind that this slows down its execution).
Parameters:
defaultValue Boolean parameter that indicates if what must be returned is the default value (true) or the actual one (false).
Returns:
A boolean value that indicates if the list of documents of the training set, ranked to the current query document, must be visualized during the validation phase.
Definition at line 741 of file DocumentClassifierApp.java.
References documentclassifier.DocumentClassifierApp.isVisualizeDocumentsList, and documentclassifier.DocumentClassifierApp.mapDefaultPreferences.
{
        return (defaultValue) ? Boolean.parseBoolean(mapDefaultPreferences.get(MapDefaultPreferences.isVISUALIZELISTRANKEDDOCUMENTS)) : isVisualizeDocumentsList;
    }
Member Data Documentation
final Preferences documentclassifier.DocumentClassifierApp.preferences = Preferences.userRoot() [static, private]
This is a variabile that contains a reference to the global application's preferences node. In this case, the reference is to the node of the user currently running the application, which can be implemented in a different way depending by the platform where the program is being executed (for example as an hidden file inside the $HOME directory in Unix systems, or as registry keys for Windows systems). Every method of this or of other classes that want to access (reading or writing) the values of the preferences, do this using the methods get and put of this variable. In this way we added an abstraction level for the access to the preferences, and if we would decide to change the preferences node containing the values of interest for this application, we'll just have to change the following line.
Definition at line 65 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.cancelPreferences(), documentclassifier.DocumentClassifierApp.getPreferences(), documentclassifier.DocumentClassifierApp.initialize(), documentclassifier.DocumentClassifierApp.preferenceChange(), and documentclassifier.DocumentClassifierApp.setKNN().
final MapDefaultPreferences documentclassifier.DocumentClassifierApp.mapDefaultPreferences = new MapDefaultPreferences() [static, private]
Map that associates the name of every preference to its default value.
Definition at line 69 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getKFold(), documentclassifier.DocumentClassifierApp.getKNN(), documentclassifier.DocumentClassifierApp.getLogFile(), documentclassifier.DocumentClassifierApp.getMapPreferences(), documentclassifier.DocumentClassifierApp.getMaximumKNNValidation(), documentclassifier.DocumentClassifierApp.getMetric(), documentclassifier.DocumentClassifierApp.getScraper(), documentclassifier.DocumentClassifierApp.getStemmer(), documentclassifier.DocumentClassifierApp.getStopWordsList(), documentclassifier.DocumentClassifierApp.getTrainingSetDirectory(), documentclassifier.DocumentClassifierApp.isLogging(), documentclassifier.DocumentClassifierApp.isOverwriteLogFile(), documentclassifier.DocumentClassifierApp.isRemovalStopWords(), documentclassifier.DocumentClassifierApp.isStemming(), documentclassifier.DocumentClassifierApp.isStratified(), documentclassifier.DocumentClassifierApp.isVisualizeCurrentDocument(), documentclassifier.DocumentClassifierApp.isVisualizeListRankedDocuments(), and documentclassifier.DocumentClassifierApp.preferenceChange().
ResourceBundle documentclassifier.DocumentClassifierApp.documentClassifierAppResources = java.util.ResourceBundle.getBundle("documentclassifier/resources/DocumentClassifierApp") [private]
Definition at line 70 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getScrapersPackageName(), and documentclassifier.DocumentClassifierApp.getStemmersPackageName().
Set<Set<Document> > documentclassifier.DocumentClassifierApp.trainingSet [private]
The current training set represented like a set of subsets of documents (the subsets are made of all the documents belonging to the same category).
Definition at line 75 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.generateTrainingSet(), and documentclassifier.DocumentClassifierApp.getTrainingSet().
int documentclassifier.DocumentClassifierApp.trainingSetSize = 0 [private]
Definition at line 76 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.generateTrainingSet(), documentclassifier.DocumentClassifierApp.getKFoldMaximum(), documentclassifier.DocumentClassifierApp.getKNNMaximum(), and documentclassifier.DocumentClassifierApp.getTrainingSetSize().
Scraper documentclassifier.DocumentClassifierApp.Scraper [private]
Configuration variables, corresponding to the preferences of the application.
Definition at line 80 of file DocumentClassifierApp.java.
String documentclassifier.DocumentClassifierApp.trainingSetDirectory [private]
Definition at line 81 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getTrainingSetDirectory(), and documentclassifier.DocumentClassifierApp.preferenceChange().
String documentclassifier.DocumentClassifierApp.logFile [private]
Definition at line 81 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getLogFile(), and documentclassifier.DocumentClassifierApp.preferenceChange().
String documentclassifier.DocumentClassifierApp.stopWordsList [private]
Definition at line 81 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getStopWordsList(), and documentclassifier.DocumentClassifierApp.preferenceChange().
String documentclassifier.DocumentClassifierApp.metric [private]
Definition at line 81 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getMetric(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isRemovalStopWords [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.Document.createHistogram(), documentclassifier.DocumentClassifierApp.isRemovalStopWords(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isStemming [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.Document.createHistogram(), documentclassifier.DocumentClassifierApp.isStemming(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isStratified [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.isStratified(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isLogging [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.isLogging(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isOverwriteLogFile [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.isOverwriteLogFile(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isVisualizeCurrentDocument [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.isVisualizeCurrentDocument(), and documentclassifier.DocumentClassifierApp.preferenceChange().
boolean documentclassifier.DocumentClassifierApp.isVisualizeDocumentsList [private]
Definition at line 82 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.isVisualizeListRankedDocuments(), and documentclassifier.DocumentClassifierApp.preferenceChange().
String documentclassifier.DocumentClassifierApp.currentStemmer [private]
Definition at line 83 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getStemmer(), and documentclassifier.DocumentClassifierApp.preferenceChange().
int documentclassifier.DocumentClassifierApp.KNN [private]
Definition at line 84 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getKNN(), documentclassifier.DocumentClassifierApp.preferenceChange(), and documentclassifier.DocumentClassifierApp.setKNN().
int documentclassifier.DocumentClassifierApp.KFold [private]
Definition at line 84 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getKFold(), and documentclassifier.DocumentClassifierApp.preferenceChange().
int documentclassifier.DocumentClassifierApp.maximumKNNValidation [private]
Definition at line 84 of file DocumentClassifierApp.java.
Referenced by documentclassifier.DocumentClassifierApp.getMaximumKNNValidation(), and documentclassifier.DocumentClassifierApp.preferenceChange().
The documentation for this class was generated from the following file:
src/documentclassifier/DocumentClassifierApp.java