DocumentClassifier: JLex.CMinimize Class Reference
JLex.CMinimize
JLex.CMinimize Class Reference
Package Functions
CMinimize ()
void min_dfa (CSpec spec)
Package Attributes
CSpec m_spec
Vector m_group
int m_ingroup []
Private Member Functions
void reset ()
void set (CSpec spec)
void col_copy (int dest, int src)
void trunc_col ()
void row_copy (int dest, int src)
boolean col_equiv (int col1, int col2)
boolean row_equiv (int row1, int row2)
void reduce ()
void fix_dtrans ()
void minimize ()
void init_groups ()
void pset (Vector dtrans_group)
void pgroups ()
Detailed Description
Definition at line 2402 of file Main.java.
Constructor & Destructor Documentation
JLex.CMinimize.CMinimize () [package]
Definition at line 2416 of file Main.java.
References JLex.CMinimize.reset().
      {
        reset();
      }
Member Function Documentation
void JLex.CMinimize.reset () [private]
Definition at line 2427 of file Main.java.
References JLex.CMinimize.m_group, JLex.CMinimize.m_ingroup, and JLex.CMinimize.m_spec.
Referenced by JLex.CMinimize.CMinimize(), and JLex.CMinimize.min_dfa().
      {
        m_spec = null;
        m_group = null;
        m_ingroup = null;
      }
void JLex.CMinimize.set (CSpec spec) [private]
Definition at line 2440 of file Main.java.
References JLex.CMinimize.m_group, JLex.CMinimize.m_ingroup, and JLex.CMinimize.m_spec.
      {
        if (CUtility.DEBUG)
          {
            CUtility.ASSERT(null != spec);
          }
        m_spec = spec;
        m_group = null;
        m_ingroup = null;
      }
void JLex.CMinimize.min_dfa (CSpec spec) [package]
Definition at line 2459 of file Main.java.
References JLex.CMinimize.minimize(), JLex.CMinimize.reduce(), and JLex.CMinimize.reset().
Referenced by JLex.CLexGen.userRules().
      {
        set(spec);
        /* Remove redundant states. */
        minimize();
        /* Column and row compression.
           Save accept states in auxilary vector. */
        reduce();
        reset();
      }
void JLex.CMinimize.col_copy (int dest, int src) [private]
Definition at line 2480 of file Main.java.
References JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_vector, and JLex.CMinimize.m_spec.
Referenced by JLex.CMinimize.reduce().
      {
        int n;
        int i;
        CDTrans dtrans;
        n = m_spec.m_dtrans_vector.size();
        for (i = 0; i < n; ++i)
          {
            dtrans = (CDTrans) m_spec.m_dtrans_vector.elementAt(i);
            dtrans.m_dtrans[dest] = dtrans.m_dtrans[src];
          }
      }
void JLex.CMinimize.trunc_col () [private]
Definition at line 2502 of file Main.java.
References JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_ncols, JLex.CSpec.m_dtrans_vector, and JLex.CMinimize.m_spec.
Referenced by JLex.CMinimize.reduce().
      {
        int n;
        int i;
        CDTrans dtrans;
        n = m_spec.m_dtrans_vector.size();
        for (i = 0; i < n; ++i)
          {
            int[] ndtrans = new int[m_spec.m_dtrans_ncols];
            dtrans = (CDTrans) m_spec.m_dtrans_vector.elementAt(i);
            System.arraycopy(dtrans.m_dtrans, 0, ndtrans, 0, ndtrans.length);
            dtrans.m_dtrans = ndtrans;
          }
      }
void JLex.CMinimize.row_copy (int dest, int src) [private]
Definition at line 2523 of file Main.java.
References JLex.CSpec.m_dtrans_vector, and JLex.CMinimize.m_spec.
Referenced by JLex.CMinimize.reduce().
      {
        CDTrans dtrans;
        dtrans = (CDTrans) m_spec.m_dtrans_vector.elementAt(src);
        m_spec.m_dtrans_vector.setElementAt(dtrans,dest);
      }
boolean JLex.CMinimize.col_equiv (int col1, int col2) [private]
Definition at line 2539 of file Main.java.
References JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_vector, and JLex.CMinimize.m_spec.
Referenced by JLex.CMinimize.reduce().
      {
        int n;
        int i;
        CDTrans dtrans;
        n = m_spec.m_dtrans_vector.size();
        for (i = 0; i < n; ++i)
          {
            dtrans = (CDTrans) m_spec.m_dtrans_vector.elementAt(i);
            if (dtrans.m_dtrans[col1] != dtrans.m_dtrans[col2])
              {
                return false;
              }
          }
        return true;
      }
boolean JLex.CMinimize.row_equiv (int row1, int row2) [private]
Definition at line 2566 of file Main.java.
References JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_ncols, JLex.CSpec.m_dtrans_vector, and JLex.CMinimize.m_spec.
Referenced by JLex.CMinimize.reduce().
      {
        int i;
        CDTrans dtrans1;
        CDTrans dtrans2;
        dtrans1 = (CDTrans) m_spec.m_dtrans_vector.elementAt(row1);
        dtrans2 = (CDTrans) m_spec.m_dtrans_vector.elementAt(row2);
        for (i = 0; i < m_spec.m_dtrans_ncols; ++i)
          {
            if (dtrans1.m_dtrans[i] != dtrans2.m_dtrans[i])
              {
                return false;
              }
          }
        return true;
      }
void JLex.CMinimize.reduce () [private]
Definition at line 2594 of file Main.java.
References JLex.CMinimize.col_copy(), JLex.CMinimize.col_equiv(), JLex.CDTrans.m_accept, JLex.CSpec.m_accept_vector, JLex.CDTrans.m_anchor, JLex.CSpec.m_anchor_array, JLex.CSpec.m_col_map, JLex.CSpec.m_dtrans_ncols, JLex.CSpec.m_dtrans_vector, JLex.CSpec.m_row_map, JLex.CMinimize.m_spec, JLex.CMinimize.row_copy(), JLex.CMinimize.row_equiv(), and JLex.CMinimize.trunc_col().
Referenced by JLex.CMinimize.min_dfa().
      {
        int i;
        int j;
        int k;
        int nrows;
        int reduced_ncols;
        int reduced_nrows;
        SparseBitSet set;
        CDTrans dtrans;
        int size;
        set = new SparseBitSet();
        /* Save accept nodes and anchor entries. */
        size = m_spec.m_dtrans_vector.size();
        m_spec.m_anchor_array = new int[size];
        m_spec.m_accept_vector = new Vector();
        for (i = 0; i < size; ++i)
          {
            dtrans = (CDTrans) m_spec.m_dtrans_vector.elementAt(i);
            m_spec.m_accept_vector.addElement(dtrans.m_accept);
            m_spec.m_anchor_array[i] = dtrans.m_anchor;
            dtrans.m_accept = null;
          }
        /* Allocate column map. */
        m_spec.m_col_map = new int[m_spec.m_dtrans_ncols];
        for (i = 0; i < m_spec.m_dtrans_ncols; ++i)
          {
            m_spec.m_col_map[i] = -1;
          }
        /* Process columns for reduction. */
        for (reduced_ncols = 0; ; ++reduced_ncols)
          {
            if (CUtility.DEBUG)
              {
                for (i = 0; i < reduced_ncols; ++i)
                  {
                    CUtility.ASSERT(-1 != m_spec.m_col_map[i]);
                  }
              }
            for (i = reduced_ncols; i < m_spec.m_dtrans_ncols; ++i)
              {
                if (-1 == m_spec.m_col_map[i])
                  {
                    break;
                  }
              }
            if (i >= m_spec.m_dtrans_ncols)
              {
                break;
              }
            if (CUtility.DEBUG)
              {
                CUtility.ASSERT(false == set.get(i));
                CUtility.ASSERT(-1 == m_spec.m_col_map[i]);
              }
            set.set(i);
            m_spec.m_col_map[i] = reduced_ncols;
            /* UNDONE: Optimize by doing all comparisons in one batch. */
            for (j = i + 1; j < m_spec.m_dtrans_ncols; ++j)
              {
                if (-1 == m_spec.m_col_map[j] && true == col_equiv(i,j))
                  {
                    m_spec.m_col_map[j] = reduced_ncols;
                  }
              }
          }
        /* Reduce columns. */
        k = 0;
        for (i = 0; i < m_spec.m_dtrans_ncols; ++i)
          {
            if (set.get(i))
              {
                ++k;
                set.clear(i);
                j = m_spec.m_col_map[i];
                if (CUtility.DEBUG)
                  {
                    CUtility.ASSERT(j <= i);
                  }
                if (j == i)
                  {
                    continue;
                  }
                col_copy(j,i);
              }
          }
        m_spec.m_dtrans_ncols = reduced_ncols;
        /* truncate m_dtrans at proper length (freeing extra) */
        trunc_col();
        if (CUtility.DEBUG)
          {
            CUtility.ASSERT(k == reduced_ncols);
          }
        /* Allocate row map. */
        nrows = m_spec.m_dtrans_vector.size();
        m_spec.m_row_map = new int[nrows];
        for (i = 0; i < nrows; ++i)
          {
            m_spec.m_row_map[i] = -1;
          }
        /* Process rows to reduce. */
        for (reduced_nrows = 0; ; ++reduced_nrows)
          {
            if (CUtility.DEBUG)
              {
                for (i = 0; i < reduced_nrows; ++i)
                  {
                    CUtility.ASSERT(-1 != m_spec.m_row_map[i]);
                  }
              }
            for (i = reduced_nrows; i < nrows; ++i)
              {
                if (-1 == m_spec.m_row_map[i])
                  {
                    break;
                  }
              }
            if (i >= nrows)
              {
                break;
              }
            if (CUtility.DEBUG)
              {
                CUtility.ASSERT(false == set.get(i));
                CUtility.ASSERT(-1 == m_spec.m_row_map[i]);
              }
            set.set(i);
            m_spec.m_row_map[i] = reduced_nrows;
            /* UNDONE: Optimize by doing all comparisons in one batch. */
            for (j = i + 1; j < nrows; ++j)
              {
                if (-1 == m_spec.m_row_map[j] && true == row_equiv(i,j))
                  {
                    m_spec.m_row_map[j] = reduced_nrows;
                  }
              }
          }
        /* Reduce rows. */
        k = 0;
        for (i = 0; i < nrows; ++i)
          {
            if (set.get(i))
              {
                ++k;
                set.clear(i);
                j = m_spec.m_row_map[i];
                if (CUtility.DEBUG)
                  {
                    CUtility.ASSERT(j <= i);
                  }
                if (j == i)
                  {
                    continue;
                  }
                row_copy(j,i);
              }
          }
        m_spec.m_dtrans_vector.setSize(reduced_nrows);
        if (CUtility.DEBUG)
          {
            /*System.out.println("k = " + k + "\nreduced_nrows = " + reduced_nrows + "");*/
            CUtility.ASSERT(k == reduced_nrows);
          }
      }
void JLex.CMinimize.fix_dtrans () [private]
Definition at line 2798 of file Main.java.
References JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_ncols, JLex.CSpec.m_dtrans_vector, JLex.CMinimize.m_group, JLex.CMinimize.m_ingroup, JLex.CMinimize.m_spec, and JLex.CSpec.m_state_dtrans.
Referenced by JLex.CMinimize.minimize().
      {
        Vector new_vector;
        int i;
        int size;
        Vector dtrans_group;
        CDTrans first;
        int c;
        new_vector = new Vector();
        size = m_spec.m_state_dtrans.length;
        for (i = 0; i < size; ++i)
          {
            if (CDTrans.F != m_spec.m_state_dtrans[i])
              {
                m_spec.m_state_dtrans[i] = m_ingroup[m_spec.m_state_dtrans[i]];
              }
          }
        size = m_group.size();
        for (i = 0; i < size; ++i)
          {
            dtrans_group = (Vector) m_group.elementAt(i);
            first = (CDTrans) dtrans_group.elementAt(0);
            new_vector.addElement(first);
            for (c = 0; c < m_spec.m_dtrans_ncols; ++c)
              {
                if (CDTrans.F != first.m_dtrans[c])
                  {
                    first.m_dtrans[c] = m_ingroup[first.m_dtrans[c]];
                  }
              }
          }
        m_group = null;
        m_spec.m_dtrans_vector = new_vector;
      }
void JLex.CMinimize.minimize () [private]
Definition at line 2844 of file Main.java.
References JLex.CMinimize.fix_dtrans(), JLex.CMinimize.init_groups(), JLex.CDTrans.m_dtrans, JLex.CSpec.m_dtrans_ncols, JLex.CMinimize.m_group, JLex.CMinimize.m_ingroup, JLex.CDTrans.m_label, JLex.CMinimize.m_spec, JLex.CSpec.m_verbose, and JLex.CMinimize.pgroups().
Referenced by JLex.CMinimize.min_dfa().
      {
        Vector dtrans_group;
        Vector new_group;
        int i;
        int j;
        int old_group_count;
        int group_count;
        CDTrans next;
        CDTrans first;
        int goto_first;
        int goto_next;
        int c;
        int group_size;
        boolean added;
        init_groups();
        group_count = m_group.size();
        old_group_count = group_count - 1;
        while (old_group_count != group_count)
          {
            old_group_count = group_count;
            if (CUtility.DEBUG)
              {
                CUtility.ASSERT(m_group.size() == group_count);
              }
            for (i = 0; i < group_count; ++i)
              {
                dtrans_group = (Vector) m_group.elementAt(i);
                group_size = dtrans_group.size();
                if (group_size <= 1)
                  {
                    continue;
                  }
                new_group = new Vector();
                added = false;
                first = (CDTrans) dtrans_group.elementAt(0);
                for (j = 1; j < group_size; ++j)
                  {
                    next = (CDTrans) dtrans_group.elementAt(j);
                    for (c = 0; c < m_spec.m_dtrans_ncols; ++c)
                      {
                        goto_first = first.m_dtrans[c];
                        goto_next = next.m_dtrans[c];
                        if (goto_first != goto_next
                            && (goto_first == CDTrans.F
                                || goto_next == CDTrans.F
                                || m_ingroup[goto_next] != m_ingroup[goto_first]))
{
                            if (CUtility.DEBUG)
{
                                CUtility.ASSERT(dtrans_group.elementAt(j) == next);
                              }
                            dtrans_group.removeElementAt(j);
                            --j;
                            --group_size;
                            new_group.addElement(next);
                            if (false == added)
{
                                added = true;
                                ++group_count;
                                m_group.addElement(new_group);
                              }
                            m_ingroup[next.m_label] = m_group.size() - 1;
                            if (CUtility.DEBUG)
{
                                CUtility.ASSERT(m_group.contains(new_group)
                                                == true);
                                CUtility.ASSERT(m_group.contains(dtrans_group)
                                                == true);
                                CUtility.ASSERT(dtrans_group.contains(first)
                                                == true);
                                CUtility.ASSERT(dtrans_group.contains(next)
                                                == false);
                                CUtility.ASSERT(new_group.contains(first)
                                                == false);
                                CUtility.ASSERT(new_group.contains(next)
                                                == true);
                                CUtility.ASSERT(dtrans_group.size() == group_size);
                                CUtility.ASSERT(i == m_ingroup[first.m_label]);
                                CUtility.ASSERT((m_group.size() - 1)
                                                == m_ingroup[next.m_label]);
                              }
                            break;
                          }
                      }
                  }
              }
          }
        System.out.println(m_group.size() + " states after removal of redundant states.");
        if (m_spec.m_verbose
            && true == CUtility.OLD_DUMP_DEBUG)
          {
            System.out.println();
            System.out.println("States grouped as follows after minimization");
            pgroups();
          }
        fix_dtrans();
      }
void JLex.CMinimize.init_groups () [private]
Definition at line 2965 of file Main.java.
References JLex.CDTrans.m_accept, JLex.CSpec.m_dtrans_vector, JLex.CMinimize.m_group, JLex.CMinimize.m_ingroup, JLex.CDTrans.m_label, JLex.CMinimize.m_spec, JLex.CSpec.m_verbose, and JLex.CMinimize.pgroups().
Referenced by JLex.CMinimize.minimize().
      {
        int i;
        int j;
        int group_count;
        int size;
        CAccept accept;
        CDTrans dtrans;
        Vector dtrans_group;
        CDTrans first;
        boolean group_found;
        m_group = new Vector();
        group_count = 0;
        size = m_spec.m_dtrans_vector.size();
        m_ingroup = new int[size];
        for (i = 0; i < size; ++i)
          {
            group_found = false;
            dtrans = (CDTrans) m_spec.m_dtrans_vector.elementAt(i);
            if (CUtility.DEBUG)
              {
                CUtility.ASSERT(i == dtrans.m_label);
                CUtility.ASSERT(false == group_found);
                CUtility.ASSERT(group_count == m_group.size());
              }
            for (j = 0; j < group_count; ++j)
              {
                dtrans_group = (Vector) m_group.elementAt(j);
                if (CUtility.DEBUG)
                  {
                    CUtility.ASSERT(false == group_found);
                    CUtility.ASSERT(0 < dtrans_group.size());
                  }
                first = (CDTrans) dtrans_group.elementAt(0);
                if (CUtility.SLOW_DEBUG)
                  {
                    CDTrans check;
                    int k;
                    int s;
                    s = dtrans_group.size();
                    CUtility.ASSERT(0 < s);
                    for (k = 1; k < s; ++k)
                      {
                        check = (CDTrans) dtrans_group.elementAt(k);
                        CUtility.ASSERT(check.m_accept == first.m_accept);
                      }
                  }
                if (first.m_accept == dtrans.m_accept)
                  {
                    dtrans_group.addElement(dtrans);
                    m_ingroup[i] = j;
                    group_found = true;
                    if (CUtility.DEBUG)
                      {
                        CUtility.ASSERT(j == m_ingroup[dtrans.m_label]);
                      }
                    break;
                  }
              }
            if (false == group_found)
              {
                dtrans_group = new Vector();
                dtrans_group.addElement(dtrans);
                m_ingroup[i] = m_group.size();
                m_group.addElement(dtrans_group);
                ++group_count;
              }
          }
        if (m_spec.m_verbose
            && true == CUtility.OLD_DUMP_DEBUG)
          {
            System.out.println("Initial grouping:");
            pgroups();
            System.out.println();
          }
      }
void JLex.CMinimize.pset (Vector dtrans_group) [private]
Definition at line 3062 of file Main.java.
References JLex.CDTrans.m_label.
Referenced by JLex.CMinimize.pgroups().
      {
        int i;
        int size;
        CDTrans dtrans;
        size = dtrans_group.size();
        for (i = 0; i < size; ++i)
          {
            dtrans = (CDTrans) dtrans_group.elementAt(i);
            System.out.print(dtrans.m_label + " ");
          }
      }
void JLex.CMinimize.pgroups () [private]
Definition at line 3082 of file Main.java.
References JLex.CSpec.m_dtrans_vector, JLex.CMinimize.m_group, JLex.CMinimize.m_ingroup, JLex.CMinimize.m_spec, and JLex.CMinimize.pset().
Referenced by JLex.CMinimize.init_groups(), and JLex.CMinimize.minimize().
      {
        int i;
        int dtrans_size;
        int group_size;
        group_size = m_group.size();
        for (i = 0; i < group_size; ++i)
          {
            System.out.print("\tGroup " + i + " {");
            pset((Vector) m_group.elementAt(i));
            System.out.println("}");
            System.out.println();
          }
        System.out.println();
        dtrans_size = m_spec.m_dtrans_vector.size();
        for (i = 0; i < dtrans_size; ++i)
          {
            System.out.println("\tstate " + i
                               + " is in group "
                               + m_ingroup[i]);
          }
      }
Member Data Documentation
CSpec JLex.CMinimize.m_spec [package]
Definition at line 2407 of file Main.java.
Referenced by JLex.CMinimize.col_copy(), JLex.CMinimize.col_equiv(), JLex.CMinimize.fix_dtrans(), JLex.CMinimize.init_groups(), JLex.CMinimize.minimize(), JLex.CMinimize.pgroups(), JLex.CMinimize.reduce(), JLex.CMinimize.reset(), JLex.CMinimize.row_copy(), JLex.CMinimize.row_equiv(), JLex.CMinimize.set(), and JLex.CMinimize.trunc_col().
Vector JLex.CMinimize.m_group [package]
Definition at line 2408 of file Main.java.
Referenced by JLex.CMinimize.fix_dtrans(), JLex.CMinimize.init_groups(), JLex.CMinimize.minimize(), JLex.CMinimize.pgroups(), JLex.CMinimize.reset(), and JLex.CMinimize.set().
int JLex.CMinimize.m_ingroup[] [package]
Definition at line 2409 of file Main.java.
Referenced by JLex.CMinimize.fix_dtrans(), JLex.CMinimize.init_groups(), JLex.CMinimize.minimize(), JLex.CMinimize.pgroups(), JLex.CMinimize.reset(), and JLex.CMinimize.set().
The documentation for this class was generated from the following file:
src/ansascraper/JLex/Main.java