DocumentClassifier: JLex.SparseBitSet Class Reference
JLex.SparseBitSet
JLex.SparseBitSet Class Reference
Public Member Functions
SparseBitSet ()
SparseBitSet (int nbits)
SparseBitSet (SparseBitSet set)
void set (int bit)
void clear (int bit)
void clearAll ()
boolean get (int bit)
void and (SparseBitSet set)
void or (SparseBitSet set)
void xor (SparseBitSet set)
int hashCode ()
int size ()
boolean equals (Object obj)
Object clone ()
Enumeration elements ()
String toString ()
Static Public Member Functions
static boolean equals (SparseBitSet a, SparseBitSet b)
static void main (String[] args)
Package Attributes
int offs []
long bits []
int size
Private Member Functions
void new_block (int bnum)
void new_block (int idx, int bnum)
void insert_block (int idx, int bnum)
int bsearch (int bnum)
boolean isValid ()
Static Private Member Functions
static final void binop (SparseBitSet a, SparseBitSet b, BinOp op)
Static Private Attributes
static final int LG_BITS = 6
static final int BITS = 1<<LG_BITS
static final int BITS_M1 = BITS-1
static final BinOp AND
static final BinOp OR
static final BinOp XOR
Classes
interface BinOp
Detailed Description
A set of bits. The set automatically grows as more bits are needed.
Version:
1.00, 25 Jul 1999
Author:
C. Scott Ananian
Definition at line 7455 of file Main.java.
Constructor & Destructor Documentation
JLex.SparseBitSet.SparseBitSet ()
Creates an empty set.
Definition at line 7472 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.SparseBitSet.main().
{
        bits = new long[4];
        offs = new int [4];
        size = 0;
    }
JLex.SparseBitSet.SparseBitSet (int nbits)
Creates an empty set with the specified size.
Parameters:
nbits the size of the set
Definition at line 7482 of file Main.java.
{
        this();
    }
JLex.SparseBitSet.SparseBitSet (SparseBitSet set)
Creates an empty set with the same size as the given set.
Definition at line 7489 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
{
        bits = new long[set.size];
        offs = new int [set.size];
        size = 0;
    }
Member Function Documentation
void JLex.SparseBitSet.new_block (int bnum) [private]
Definition at line 7495 of file Main.java.
References JLex.SparseBitSet.bsearch().
Referenced by JLex.SparseBitSet.clear(), and JLex.SparseBitSet.set().
{
        new_block(bsearch(bnum), bnum);
    }
void JLex.SparseBitSet.new_block (int idx, int bnum) [private]
Definition at line 7498 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.insert_block(), JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
{
        if (size==bits.length) { // resize
            long[] nbits = new long[size*3];
            int [] noffs = new int [size*3];
            System.arraycopy(bits, 0, nbits, 0, size);
            System.arraycopy(offs, 0, noffs, 0, size);
            bits = nbits;
            offs = noffs;
        }
        CUtility.ASSERT(size<bits.length);
        insert_block(idx, bnum);
    }
void JLex.SparseBitSet.insert_block (int idx, int bnum) [private]
Definition at line 7510 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.SparseBitSet.new_block().
{
        CUtility.ASSERT(idx<=size);
        CUtility.ASSERT(idx==size || offs[idx]!=bnum);
        System.arraycopy(bits, idx, bits, idx+1, size-idx);
        System.arraycopy(offs, idx, offs, idx+1, size-idx);
        offs[idx]=bnum;
        bits[idx]=0; //clear them bits.
        size++;
    }
int JLex.SparseBitSet.bsearch (int bnum) [private]
Definition at line 7519 of file Main.java.
References JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.SparseBitSet.clear(), JLex.SparseBitSet.get(), JLex.SparseBitSet.new_block(), and JLex.SparseBitSet.set().
{
        int l=0, r=size; // search interval is [l, r)
        while (l<r) {
            int p = (l+r)/2;
            if (bnum<offs[p]) r=p;
            else if (bnum>offs[p]) l=p+1;
            else return p;
        }
        CUtility.ASSERT(l==r);
        return l; // index at which the bnum *should* be, if it's not.
    }
void JLex.SparseBitSet.set (int bit)
Sets a bit.
Parameters:
bit the bit to be set
Definition at line 7535 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.BITS_M1, JLex.SparseBitSet.bsearch(), JLex.SparseBitSet.LG_BITS, JLex.SparseBitSet.new_block(), JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.CSet.add(), JLex.CSimplifyNfa.computeClasses(), JLex.CNfa2Dfa.e_closure(), JLex.CLexGen.getStates(), JLex.CMakeNfa.machine(), JLex.SparseBitSet.main(), JLex.CNfa2Dfa.make_dtrans(), JLex.CSet.map(), and JLex.CNfa2Dfa.move().
{
        int bnum = bit >> LG_BITS;
        int idx  = bsearch(bnum);
        if (idx >= size || offs[idx]!=bnum)
            new_block(idx, bnum);
        bits[idx] |= (1L << (bit & BITS_M1) );
    }
void JLex.SparseBitSet.clear (int bit)
Clears a bit.
Parameters:
bit the bit to be cleared
Definition at line 7547 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.BITS_M1, JLex.SparseBitSet.bsearch(), JLex.SparseBitSet.LG_BITS, JLex.SparseBitSet.new_block(), JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.SparseBitSet.main().
{
        int bnum = bit >> LG_BITS;
        int idx  = bsearch(bnum);
        if (idx >= size || offs[idx]!=bnum)
            new_block(idx, bnum);
        bits[idx] &= ~(1L << (bit & BITS_M1) );
    }
void JLex.SparseBitSet.clearAll ()
Clears all bits.
Definition at line 7558 of file Main.java.
References JLex.SparseBitSet.size().
Referenced by JLex.CSimplifyNfa.computeClasses(), JLex.SparseBitSet.main(), and JLex.CSet.map().
{
        size = 0;
    }
boolean JLex.SparseBitSet.get (int bit)
Gets a bit.
Parameters:
bit the bit to be gotten
Definition at line 7566 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.BITS_M1, JLex.SparseBitSet.bsearch(), JLex.SparseBitSet.LG_BITS, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.CSimplifyNfa.computeClasses(), JLex.CSet.contains(), JLex.CNfa2Dfa.e_closure(), JLex.SparseBitSet.main(), and JLex.CMakeNfa.processStates().
{
        int bnum = bit >> LG_BITS;
        int idx  = bsearch(bnum);
        if (idx >= size || offs[idx]!=bnum)
            return false;
        return 0 != ( bits[idx] & (1L << (bit & BITS_M1) ) );
    }
void JLex.SparseBitSet.and (SparseBitSet set)
Logically ANDs this bit set with the specified set of bits.
Parameters:
set the bit set to be ANDed with
Definition at line 7578 of file Main.java.
References JLex.SparseBitSet.AND, and JLex.SparseBitSet.binop().
Referenced by JLex.CSimplifyNfa.computeClasses(), and JLex.SparseBitSet.main().
{
        binop(this, set, AND);
    }
void JLex.SparseBitSet.or (SparseBitSet set)
Logically ORs this bit set with the specified set of bits.
Parameters:
set the bit set to be ORed with
Definition at line 7586 of file Main.java.
References JLex.SparseBitSet.binop(), and JLex.SparseBitSet.OR.
Referenced by JLex.SparseBitSet.main().
{
        binop(this, set, OR);
    }
void JLex.SparseBitSet.xor (SparseBitSet set)
Logically XORs this bit set with the specified set of bits.
Parameters:
set the bit set to be XORed with
Definition at line 7594 of file Main.java.
References JLex.SparseBitSet.binop(), and JLex.SparseBitSet.XOR.
Referenced by JLex.SparseBitSet.main().
{
        binop(this, set, XOR);
    }
static final void JLex.SparseBitSet.binop (SparseBitSet a, SparseBitSet b, BinOp op) [static, private]
Definition at line 7611 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, JLex.SparseBitSet.BinOp.op(), and JLex.SparseBitSet.size.
Referenced by JLex.SparseBitSet.and(), JLex.SparseBitSet.or(), and JLex.SparseBitSet.xor().
{
        int  nsize = a.size + b.size;
        long[] nbits;
        int [] noffs;
        int a_zero, a_size;
        // be very clever and avoid allocating more memory if we can.
        if (a.bits.length < nsize) { // oh well, have to make working space.
            nbits = new long[nsize];
            noffs = new int [nsize];
            a_zero  = 0; a_size = a.size;
        } else { // reduce, reuse, recycle!
            nbits = a.bits;
            noffs = a.offs;
            a_zero = a.bits.length - a.size; a_size = a.bits.length;
            System.arraycopy(a.bits, 0, a.bits, a_zero, a.size);
            System.arraycopy(a.offs, 0, a.offs, a_zero, a.size);
        }
        // ok, crunch through and binop those sets!
        nsize = 0;
        for (int i=a_zero, j=0; i<a_size || j<b.size; ) {
            long nb; int no;
            if (i<a_size && (j>=b.size || a.offs[i] < b.offs[j])) {
                nb = op.op(a.bits[i], 0);
                no = a.offs[i];
                i++;
            } else if (j<b.size && (i>=a_size || a.offs[i] > b.offs[j])) {
                nb = op.op(0, b.bits[j]);
                no = b.offs[j];
                j++;
            } else { // equal keys; merge.
                nb = op.op(a.bits[i], b.bits[j]);
                no = a.offs[i];
                i++; j++;
            }
            if (nb!=0) {
                nbits[nsize] = nb;
                noffs[nsize] = no;
                nsize++;
            }
        }
        a.bits = nbits;
        a.offs = noffs;
        a.size = nsize;
    }
int JLex.SparseBitSet.hashCode ()
Gets the hashcode.
Definition at line 7659 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
{
        long h = 1234;
        for (int i=0; i<size; i++)
            h ^= bits[i] * offs[i];
        return (int)((h >> 32) ^ h);
    }
int JLex.SparseBitSet.size ()
Calculates and returns the set's size
Definition at line 7669 of file Main.java.
References JLex.SparseBitSet.LG_BITS, and JLex.SparseBitSet.offs.
Referenced by JLex.SparseBitSet.bsearch(), JLex.SparseBitSet.clear(), JLex.SparseBitSet.clearAll(), JLex.SparseBitSet.elements(), JLex.SparseBitSet.get(), JLex.SparseBitSet.hashCode(), JLex.SparseBitSet.insert_block(), JLex.SparseBitSet.isValid(), JLex.SparseBitSet.new_block(), JLex.SparseBitSet.set(), and JLex.SparseBitSet.SparseBitSet().
                      {
        return (size==0)?0:((1+offs[size-1]) << LG_BITS);
    }
boolean JLex.SparseBitSet.equals (Object obj)
Compares this object against the specified object.
Parameters:
obj the object to commpare with
Returns:
true if the objects are the same; false otherwise.
Definition at line 7678 of file Main.java.
Referenced by JLex.SparseBitSet.main().
{
        if ((obj != null) && (obj instanceof SparseBitSet))
            return equals(this, (SparseBitSet)obj);
        return false;
    }
static boolean JLex.SparseBitSet.equals (SparseBitSet a, SparseBitSet b) [static]
Compares two SparseBitSets for equality.
Returns:
true if the objects are the same; false otherwise.
Definition at line 7687 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size.
{
        for (int i=0, j=0; i<a.size || j<b.size; ) {
            if (i<a.size && (j>=b.size || a.offs[i] < b.offs[j])) {
                if (a.bits[i++]!=0) return false;
            } else if (j<b.size && (i>=a.size || a.offs[i] > b.offs[j])) {
                if (b.bits[j++]!=0) return false;
            } else { // equal keys
                if (a.bits[i++]!=b.bits[j++]) return false;
            }
        }
        return true;
    }
Object JLex.SparseBitSet.clone ()
Clones the SparseBitSet.
Definition at line 7703 of file Main.java.
References JLex.SparseBitSet.bits, and JLex.SparseBitSet.offs.
Referenced by JLex.CNfa2Dfa.add_to_dstates(), JLex.SparseBitSet.main(), JLex.CNfa.mimic(), and JLex.CSet.mimic().
{
        try {
            SparseBitSet set = (SparseBitSet)super.clone();
            set.bits = (long[]) bits.clone();
            set.offs = (int []) offs.clone();
            return set;
        } catch (CloneNotSupportedException e) {
            // this shouldn't happen, since we are Cloneable
            throw new InternalError();
        }
    }
Enumeration JLex.SparseBitSet.elements ()
Return an Enumeration of Integers which represent set bit indices in this SparseBitSet.
Definition at line 7719 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.BITS, JLex.SparseBitSet.LG_BITS, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
Referenced by JLex.CSet.map(), and JLex.SparseBitSet.toString().
{
        return new Enumeration() {
            int idx=-1, bit=BITS;
            { advance(); }
            public boolean hasMoreElements() {
                return (idx<size);
            }
            public Object nextElement() {
                int r = bit + (offs[idx] << LG_BITS);
                advance();
                return new Integer(r);
            }
            private void advance() {
                while (idx<size) {
                    while (++bit<BITS)
                        if (0!=(bits[idx] & (1L<<bit)))
                            return;
                    idx++; bit=-1;
                }
            }
        };
    }
String JLex.SparseBitSet.toString ()
Converts the SparseBitSet to a String.
Definition at line 7744 of file Main.java.
References JLex.SparseBitSet.elements().
{
        StringBuffer sb = new StringBuffer();
        sb.append('{');
        for (Enumeration e=elements(); e.hasMoreElements(); ) {
            if (sb.length() > 1) sb.append(", ");
            sb.append(e.nextElement());
        }
        sb.append('}');
        return sb.toString();
    }
boolean JLex.SparseBitSet.isValid () [private]
Check validity.
Definition at line 7756 of file Main.java.
References JLex.SparseBitSet.bits, JLex.SparseBitSet.offs, and JLex.SparseBitSet.size().
{
        if (bits.length!=offs.length) return false;
        if (size>bits.length) return false;
        if (size!=0 && 0<=offs[0]) return false;
        for (int i=1; i<size; i++)
            if (offs[i] < offs[i-1])
                    return false;
        return true;
    }
static void JLex.SparseBitSet.main (String[] args) [static]
Self-test.
Definition at line 7766 of file Main.java.
References JLex.SparseBitSet.and(), JLex.SparseBitSet.clear(), JLex.SparseBitSet.clearAll(), JLex.SparseBitSet.clone(), JLex.SparseBitSet.equals(), JLex.SparseBitSet.get(), JLex.SparseBitSet.or(), JLex.SparseBitSet.set(), JLex.SparseBitSet.size, JLex.SparseBitSet.SparseBitSet(), and JLex.SparseBitSet.xor().
{
        final int ITER = 500;
        final int RANGE= 65536;
        SparseBitSet a = new SparseBitSet();
        CUtility.ASSERT(!a.get(0) && !a.get(1));
        CUtility.ASSERT(!a.get(123329));
        a.set(0); CUtility.ASSERT(a.get(0) && !a.get(1));
        a.set(1); CUtility.ASSERT(a.get(0) && a.get(1));
        a.clearAll();
        CUtility.ASSERT(!a.get(0) && !a.get(1));
        java.util.Random r = new java.util.Random();
        java.util.Vector v = new java.util.Vector();
        for (int n=0; n<ITER; n++) {
            int rr = ((r.nextInt()>>>1) % RANGE) << 1;
            a.set(rr); v.addElement(new Integer(rr));
            // check that all the numbers are there.
            CUtility.ASSERT(a.get(rr) && !a.get(rr+1) && !a.get(rr-1));
            for (int i=0; i<v.size(); i++)
                CUtility.ASSERT(a.get(((Integer)v.elementAt(i)).intValue()));
        }
        SparseBitSet b = (SparseBitSet) a.clone();
        CUtility.ASSERT(a.equals(b) && b.equals(a));
        for (int n=0; n<ITER/2; n++) {
            int rr = (r.nextInt()>>>1) % v.size();
            int m = ((Integer)v.elementAt(rr)).intValue();
            b.clear(m); v.removeElementAt(rr);
            // check that numbers are removed properly.
            CUtility.ASSERT(!b.get(m));
        }
        CUtility.ASSERT(!a.equals(b));
        SparseBitSet c = (SparseBitSet) a.clone();
        SparseBitSet d = (SparseBitSet) a.clone();
        c.and(a);
        CUtility.ASSERT(c.equals(a) && a.equals(c));
        c.xor(a);
        CUtility.ASSERT(!c.equals(a) && c.size()==0);
        d.or(b);
        CUtility.ASSERT(d.equals(a) && !b.equals(d));
        d.and(b);
        CUtility.ASSERT(!d.equals(a) && b.equals(d));
        d.xor(a);
        CUtility.ASSERT(!d.equals(a) && !b.equals(d));
        c.or(d); c.or(b);
        CUtility.ASSERT(c.equals(a) && a.equals(c));
        c = (SparseBitSet) d.clone();
        c.and(b);
        CUtility.ASSERT(c.size()==0);
        System.out.println("Success.");
    }
Member Data Documentation
int JLex.SparseBitSet.offs[] [package]
Sorted array of bit-block offsets.
Definition at line 7457 of file Main.java.
Referenced by JLex.SparseBitSet.binop(), JLex.SparseBitSet.bsearch(), JLex.SparseBitSet.clear(), JLex.SparseBitSet.clone(), JLex.SparseBitSet.elements(), JLex.SparseBitSet.equals(), JLex.SparseBitSet.get(), JLex.SparseBitSet.hashCode(), JLex.SparseBitSet.insert_block(), JLex.SparseBitSet.isValid(), JLex.SparseBitSet.new_block(), JLex.SparseBitSet.set(), JLex.SparseBitSet.size(), and JLex.SparseBitSet.SparseBitSet().
long JLex.SparseBitSet.bits[] [package]
Array of bit-blocks; each holding BITS bits.
Definition at line 7459 of file Main.java.
Referenced by JLex.SparseBitSet.binop(), JLex.SparseBitSet.clear(), JLex.SparseBitSet.clone(), JLex.SparseBitSet.elements(), JLex.SparseBitSet.equals(), JLex.SparseBitSet.get(), JLex.SparseBitSet.hashCode(), JLex.SparseBitSet.insert_block(), JLex.SparseBitSet.isValid(), JLex.SparseBitSet.new_block(), JLex.SparseBitSet.set(), and JLex.SparseBitSet.SparseBitSet().
int JLex.SparseBitSet.size [package]
Number of blocks currently in use.
Definition at line 7461 of file Main.java.
Referenced by JLex.SparseBitSet.binop(), JLex.CSimplifyNfa.computeClasses(), JLex.SparseBitSet.equals(), JLex.SparseBitSet.main(), and JLex.CNfa2Dfa.move().
final int JLex.SparseBitSet.LG_BITS = 6 [static, private]
log base 2 of BITS, for the identity: x/BITS == x >> LG_BITS
Definition at line 7463 of file Main.java.
Referenced by JLex.SparseBitSet.clear(), JLex.SparseBitSet.elements(), JLex.SparseBitSet.get(), JLex.SparseBitSet.set(), and JLex.SparseBitSet.size().
final int JLex.SparseBitSet.BITS = 1<<LG_BITS [static, private]
Number of bits in a block.
Definition at line 7465 of file Main.java.
Referenced by JLex.SparseBitSet.elements().
final int JLex.SparseBitSet.BITS_M1 = BITS-1 [static, private]
BITS-1, using the identity: x % BITS == x & (BITS-1)
Definition at line 7467 of file Main.java.
Referenced by JLex.SparseBitSet.clear(), JLex.SparseBitSet.get(), and JLex.SparseBitSet.set().
final BinOp JLex.SparseBitSet.AND [static, private]
Initial value:
 new BinOp() {
        public final long op(long a, long b) { return a & b; }
    }
Definition at line 7602 of file Main.java.
Referenced by JLex.SparseBitSet.and().
final BinOp JLex.SparseBitSet.OR [static, private]
Initial value:
 new BinOp() {
        public final long op(long a, long b) { return a | b; }
    }
Definition at line 7605 of file Main.java.
Referenced by JLex.SparseBitSet.or().
final BinOp JLex.SparseBitSet.XOR [static, private]
Initial value:
 new BinOp() {
        public final long op(long a, long b) { return a ^ b; }
    }
Definition at line 7608 of file Main.java.
Referenced by JLex.SparseBitSet.xor().
The documentation for this class was generated from the following file:
src/ansascraper/JLex/Main.java